[[ImageMagick]]
arch = "aarch64"
git-tree-sha1 = "7d68a73878c2cb19f0afb00a068e7a5b4156656a"
os = "macos"

    [[ImageMagick.download]]
    sha256 = "05b0af9318036e28883c3284f8181ab912ac2ecfc700d0899f1ee969de871b30"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.12+1/ImageMagick.v6.9.12.aarch64-apple-darwin.tar.gz"
[[ImageMagick]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3b8bd88b6309743179430c987e5b8803f9df1873"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "6e97d7ed01bb90a432d595931c532c847b029e64c8dc752ed4220d881cd65f9c"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.12+1/ImageMagick.v6.9.12.aarch64-linux-gnu-cxx03.tar.gz"
[[ImageMagick]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "24b6c09e54730a3c0dc19002d5646de52b8906f8"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "343537e4205da2f967956cb267b6f74f4feb803a45fe7f295c4fcf8fb6b47499"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.12+1/ImageMagick.v6.9.12.aarch64-linux-gnu-cxx11.tar.gz"
[[ImageMagick]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f4be938aaa12fe032d8f756663a12ada36c94b42"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "2d3bcd1a59284e6168d176d99def1dbb635409608ec1505925288992bf6f0d8d"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.12+1/ImageMagick.v6.9.12.aarch64-linux-musl-cxx03.tar.gz"
[[ImageMagick]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "123e7a4ce12fdc9d42b59c6360fd1164e31f8165"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "7be84b8b7df9bf8df1be983aee3ce4c2301ce99e8f910cad193a4fbfcda8a81c"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.12+1/ImageMagick.v6.9.12.aarch64-linux-musl-cxx11.tar.gz"
[[ImageMagick]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "02a860d0ec9eeae413fa66bceb955eae003af0c0"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "73db7e3775e59ba497d217be305fc83be3285fe9fdf2543d013715634ca0d6fe"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.12+1/ImageMagick.v6.9.12.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[ImageMagick]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "346838037995a4d48a96a1ed1fae6d9a79de4b9c"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "cf22b8fd0de09d509cd009e4a8d9d7bb2c291a5ebf68bef2a84920b2c93e75f2"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.12+1/ImageMagick.v6.9.12.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[ImageMagick]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "be2b709bbce6211afee0b9c1ed03278635eae0a2"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "2e327d4d133e0b2eaac609b621a5ffe82b706ee5e908f03d42c54219bca0a541"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.12+1/ImageMagick.v6.9.12.armv6l-linux-musleabihf-cxx03.tar.gz"
[[ImageMagick]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8b66c16ee55294b3cb918963395759d9bab07fe4"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "fb3c6bb80b3a1a62dcbf88fb3bc4377338540561d5545e3a1a2799bc4c91711c"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.12+1/ImageMagick.v6.9.12.armv6l-linux-musleabihf-cxx11.tar.gz"
[[ImageMagick]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3be3e98701539806399e33fd5c1376ec3bf75fce"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "8cf96d70d4527777bec7c12f520e8031650d0bf001eeb7cc45e50070f0f2e31c"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.12+1/ImageMagick.v6.9.12.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[ImageMagick]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b887efc65d49c9886f613918d3840b6abfc45f87"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "d2c1086ff1020a2dcfdf7627dacc69fce3d275fb7d142594699e6da534b45b71"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.12+1/ImageMagick.v6.9.12.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[ImageMagick]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b6bf704eebb475592c178136912cb78b345b3563"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "5ed871881e3ab52d5fafa4c8a9127fe971bf66adc74d16cb3229b86ae43ad346"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.12+1/ImageMagick.v6.9.12.armv7l-linux-musleabihf-cxx03.tar.gz"
[[ImageMagick]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dde6731c32a49c25fb133567214c746cd24bc501"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "cf808b01b909f6f571fedafa37dfeba5d99503c7411e9ab448026e34055395b0"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.12+1/ImageMagick.v6.9.12.armv7l-linux-musleabihf-cxx11.tar.gz"
[[ImageMagick]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d70498703303b8233933a9c273b545aa1728c7e5"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "376c4b1b6020087b7b943d51e1d0812a242435ae35405236c5f12f1ccb5be322"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.12+1/ImageMagick.v6.9.12.i686-linux-gnu-cxx03.tar.gz"
[[ImageMagick]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f61ad090ab4d5de3518f61efac4a50457f85bfe0"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "9da2a038a64e08fc7f5c72533ed63710191a4a992f409bc01edbd000a2950d1a"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.12+1/ImageMagick.v6.9.12.i686-linux-gnu-cxx11.tar.gz"
[[ImageMagick]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ed8ec1c25a8db1647e8005ca8f5b945219e35f46"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "52a600f9c87c72c1538db30e281111e3b44d83e31f1ed5e237780bcc06b797db"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.12+1/ImageMagick.v6.9.12.i686-linux-musl-cxx03.tar.gz"
[[ImageMagick]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bfd7202960f3f9af3b36c8d5bbf5b6323f55a32e"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "f7ab47a030dfe22cd3893b928517e51cae4eb8762e44bfde7a7860e1fdfc1f6a"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.12+1/ImageMagick.v6.9.12.i686-linux-musl-cxx11.tar.gz"
[[ImageMagick]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "14c40f2153d03be766ac13593f0f9d24a2039b9b"
os = "windows"

    [[ImageMagick.download]]
    sha256 = "d15408a7b3a4f0d2dc8bf67b47b022d639d4c24dce6ac3f9c3f3c5b8d7af28cc"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.12+1/ImageMagick.v6.9.12.i686-w64-mingw32-cxx03.tar.gz"
[[ImageMagick]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "695cdd5b50e74270c683928924086f7b3b85ee0d"
os = "windows"

    [[ImageMagick.download]]
    sha256 = "9a60c8e2296c7e3a5d944a53fa4e1d1bfe318012d00b54fbcff4124f29d70d04"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.12+1/ImageMagick.v6.9.12.i686-w64-mingw32-cxx11.tar.gz"
[[ImageMagick]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2f85e5da2185dee51c6cdb5d5f4f092059ba1897"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "62e551d00b5cbe7a72f64b71a4c7ef309f0fabdcd6138a4b58ca8930f6011797"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.12+1/ImageMagick.v6.9.12.powerpc64le-linux-gnu-cxx03.tar.gz"
[[ImageMagick]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2609a2a199dd74c7f7d4f6f03ac396c4cfc88f8f"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "97e73db939f26537ee5dbc844768f55cb7b9350f9846cd3dd1b061add3404900"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.12+1/ImageMagick.v6.9.12.powerpc64le-linux-gnu-cxx11.tar.gz"
[[ImageMagick]]
arch = "x86_64"
git-tree-sha1 = "590ac0512ac91a99dcdcdb7bad30f9ddd74f8457"
os = "macos"

    [[ImageMagick.download]]
    sha256 = "93384a822eed0f89e53082e99b06997ec530d9bfe441e29b34f7cda0497387de"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.12+1/ImageMagick.v6.9.12.x86_64-apple-darwin.tar.gz"
[[ImageMagick]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ae7337384f34c8830eafad8adae0285de6b9fe36"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "5bec7823aadc347f9cc3fa9bf8635f94069a7150e6553974e490c456472e2053"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.12+1/ImageMagick.v6.9.12.x86_64-linux-gnu-cxx03.tar.gz"
[[ImageMagick]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "28f03f1c9ffca0bd981df80908bc6068171f74c1"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "934f4306b3801da939a60a308f483560eaa3b0c3c27d52a89808f0ae82f7bf9e"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.12+1/ImageMagick.v6.9.12.x86_64-linux-gnu-cxx11.tar.gz"
[[ImageMagick]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f735f48d9767b441eb89603ac4b6f394de362d94"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "d1bb783ed641bde00fdad658940073cf9e8291959384cedad102d3128a5bd3ec"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.12+1/ImageMagick.v6.9.12.x86_64-linux-musl-cxx03.tar.gz"
[[ImageMagick]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "173ca42a395120a92d6b5838a9f23220b00164e4"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "a6d5b1171722f8f4864fec9f8d583e2669308292bfb13670e837426d8a19228e"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.12+1/ImageMagick.v6.9.12.x86_64-linux-musl-cxx11.tar.gz"
[[ImageMagick]]
arch = "x86_64"
git-tree-sha1 = "dc0efbd11a249ceab48ac5f3266f95932aeae9fb"
os = "freebsd"

    [[ImageMagick.download]]
    sha256 = "4a41df9f629b362aec389feb0163dd6bb851abfcc5c050db401264d680ac2e40"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.12+1/ImageMagick.v6.9.12.x86_64-unknown-freebsd.tar.gz"
[[ImageMagick]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "da883214fd51195aa136604d09c1c0a020038161"
os = "windows"

    [[ImageMagick.download]]
    sha256 = "53262f3210e2bd36dda9377a9ef80c2d63d4f2ce9fcff05d64341fc68084cd59"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.12+1/ImageMagick.v6.9.12.x86_64-w64-mingw32-cxx03.tar.gz"
[[ImageMagick]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fb050c4242f4d8c1ea128b1e0f521c449e630826"
os = "windows"

    [[ImageMagick.download]]
    sha256 = "a1c149040753bbfcff76e338e020aa1afa922fdaf46b1c74d6b227c0dfb4070f"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.12+1/ImageMagick.v6.9.12.x86_64-w64-mingw32-cxx11.tar.gz"
