[[ImageMagick]]
arch = "aarch64"
git-tree-sha1 = "48156f518a7ce6ed626bca36acfc1b3b169ac49c"
os = "macos"

    [[ImageMagick.download]]
    sha256 = "6980ee94f6eac4ea6025ad8fadf374757c14e32838834a99ab191fefd70756bd"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13026+0/ImageMagick.v6.9.13026.aarch64-apple-darwin.tar.gz"
[[ImageMagick]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f69ae5078510fffe900ea797f91baef819cc0651"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "b8b669291654f216900af8ddc17a00f9af66a04da8c6a80df215972010f72719"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13026+0/ImageMagick.v6.9.13026.aarch64-linux-gnu-cxx03.tar.gz"
[[ImageMagick]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "908ace0dca143829f79f47a9078fdf65f96f52bd"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "dabe82f87c6cf7d61dd9b2bd6aa65504ff3b0ab114428de3d9272bdb2c1e2513"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13026+0/ImageMagick.v6.9.13026.aarch64-linux-gnu-cxx11.tar.gz"
[[ImageMagick]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7a85f7e5c4fd896b4e709add78c594e47dcfd721"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "146281c0ba4addf39da62df802dbccd4d250d749842ccb0d346c343de0829e69"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13026+0/ImageMagick.v6.9.13026.aarch64-linux-musl-cxx03.tar.gz"
[[ImageMagick]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d0af9f0f11833a9fbcb72bff5842d61ca8339ffd"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "850ca2383a18019b2801fdb9a83035292f9f5210ec13938f1af40fe88398b802"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13026+0/ImageMagick.v6.9.13026.aarch64-linux-musl-cxx11.tar.gz"
[[ImageMagick]]
arch = "aarch64"
git-tree-sha1 = "d578c4cac1579a2d62445f4f6aa2d4d8210eb745"
os = "freebsd"

    [[ImageMagick.download]]
    sha256 = "0411b50cda7ccd01b47c942b8f79003083d74b92d2df71e751c7f0e39eda1cae"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13026+0/ImageMagick.v6.9.13026.aarch64-unknown-freebsd.tar.gz"
[[ImageMagick]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "68619d6721193fb2ac70b202b2dc40066ab325a1"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "2e9f578932e621ed29a1cf272230a9cd4f86a32001eac7fd67b45d8a016fa873"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13026+0/ImageMagick.v6.9.13026.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[ImageMagick]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4cae5e95f6c43b34065de0bad6f7dbbb61b85a9d"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "3d317409ef0b9f9236f93ffd94044c72da745be436c9bb03b8cc48d158be6ceb"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13026+0/ImageMagick.v6.9.13026.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[ImageMagick]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "73586505883e6148ea2bb6ab9799f32acde0e406"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "1101f718a0790f8019734dad125061d07ef8d406612f11329fbef572273b2cc0"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13026+0/ImageMagick.v6.9.13026.armv6l-linux-musleabihf-cxx03.tar.gz"
[[ImageMagick]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "99083fc66d25115eb7f2a838adada141d96fb4f7"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "3b335aa756588db4f94c37eebf1ad9082e738b84568376246d65a2c2752ea11d"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13026+0/ImageMagick.v6.9.13026.armv6l-linux-musleabihf-cxx11.tar.gz"
[[ImageMagick]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "80d80148438f55218e9a2e797a73133cf1457f61"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "0740c0b4d8ba62cc7ca59f9339a21940ca550d33480c9e2dbbe933cab91a6fde"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13026+0/ImageMagick.v6.9.13026.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[ImageMagick]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "900ab3756247fe74f8d124ed79eb0c3b21470b33"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "10a2352cd0a8c1923f72b0f2d5f6fdcc4ce4e99e22348e124732e0f696b886d9"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13026+0/ImageMagick.v6.9.13026.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[ImageMagick]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "782740b7183e9c7f819f53798e4bacc4ea24ce48"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "4e241eccb4b4c41483f78ebe747f2062c59f0a5453deba61b18c0ac0fd0a4004"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13026+0/ImageMagick.v6.9.13026.armv7l-linux-musleabihf-cxx03.tar.gz"
[[ImageMagick]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4e163305c83998437410d91e8f8423be0f38d755"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "2b85ab5d2293f9683fc99581426bf0dc3e823de4a816a2af687bf64aacad40e9"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13026+0/ImageMagick.v6.9.13026.armv7l-linux-musleabihf-cxx11.tar.gz"
[[ImageMagick]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "60c3d4836069986198646e7f76782be03e2ac5d7"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "59320eaa32864a6ffe7b0be9896da81efef2c6b745b6eb30e18fdba126d61882"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13026+0/ImageMagick.v6.9.13026.i686-linux-gnu-cxx03.tar.gz"
[[ImageMagick]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f01637d001ff173a3492579dd7fa5204d411d97d"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "900bb5dd2c63c5103d309b0953439ee95ce863538ef991b9c0086211072ade6d"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13026+0/ImageMagick.v6.9.13026.i686-linux-gnu-cxx11.tar.gz"
[[ImageMagick]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "781577ba0f661906292f8a420bf5d1d4a922cabf"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "2af28aae3e2f9b874153db92491628c0e1881cf0c6a92dc1c8fc2ecce08d3b31"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13026+0/ImageMagick.v6.9.13026.i686-linux-musl-cxx03.tar.gz"
[[ImageMagick]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ec3a4408dfb020d1cc31b273ef7a203de5751b0f"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "8a94beb14bc0ead39abfc92b380436eeb58486c2a5fb45f14cede9964acb39f3"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13026+0/ImageMagick.v6.9.13026.i686-linux-musl-cxx11.tar.gz"
[[ImageMagick]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f839157080efca75dbc8d08324b55380d222a348"
os = "windows"

    [[ImageMagick.download]]
    sha256 = "cb92e38a032a6785b00717df892298f4db92650fe27fe48064d1d7849f7f22ec"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13026+0/ImageMagick.v6.9.13026.i686-w64-mingw32-cxx03.tar.gz"
[[ImageMagick]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c54bbca41a23fac538b8a7885f0448558ae20138"
os = "windows"

    [[ImageMagick.download]]
    sha256 = "8645948aa23600d8ece38c644ad4c9f63d827ba38042b78f755f784720eb7a4e"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13026+0/ImageMagick.v6.9.13026.i686-w64-mingw32-cxx11.tar.gz"
[[ImageMagick]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bb85d3108a9e6d38c99448dc0f07a4a84be8699f"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "79d04fd90376d0eaf53412522ad5c0cf5ffac702611a47a0f9082db8d56be018"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13026+0/ImageMagick.v6.9.13026.powerpc64le-linux-gnu-cxx03.tar.gz"
[[ImageMagick]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "776ef83a60f2bc239f1a4de99d9c9a48f6a9a58b"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "4ac89c34b20977516d5c159186166686293a1d57a07f1790c67c750f149183e4"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13026+0/ImageMagick.v6.9.13026.powerpc64le-linux-gnu-cxx11.tar.gz"
[[ImageMagick]]
arch = "riscv64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d35b982b329dd1c50a4814e3d7f143263eb9cdd7"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "976760a3cbbc2af0d143bd80782d70beeda2adbdb7236b56575f7e11ec12349b"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13026+0/ImageMagick.v6.9.13026.riscv64-linux-gnu-cxx03.tar.gz"
[[ImageMagick]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "26ba6ba9edba4403ba2493294624a198030f9797"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "094d87b375311702423921853b408f93578460211b9d10d5eadf73df79640591"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13026+0/ImageMagick.v6.9.13026.riscv64-linux-gnu-cxx11.tar.gz"
[[ImageMagick]]
arch = "x86_64"
git-tree-sha1 = "da8d328b7caaa269024b48f037e9637b06f6d4cd"
os = "macos"

    [[ImageMagick.download]]
    sha256 = "3edd014f45d231a9329196b98855b7b4d8d722331add76b057495257ae1a2198"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13026+0/ImageMagick.v6.9.13026.x86_64-apple-darwin.tar.gz"
[[ImageMagick]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "001de48b216e58b0a1c7b106d7f8a173936ef91f"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "4676b8f79080d50a5608706273fb8dac3f7a3595750c9668912b583acebd3834"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13026+0/ImageMagick.v6.9.13026.x86_64-linux-gnu-cxx03.tar.gz"
[[ImageMagick]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "584c923bb4a9786d6528dbcb185ffe7d0a55653b"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "4f7833d984a192d8705b58a971af57ce7e0c43e27ac9d324a5d63b73902fbbf9"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13026+0/ImageMagick.v6.9.13026.x86_64-linux-gnu-cxx11.tar.gz"
[[ImageMagick]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1513b2815b0a254781c181d80c8a220f8846c990"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "84754104136bf887eddb04dfc198d401b53ca002a97cdae23f6e6fbc002981cd"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13026+0/ImageMagick.v6.9.13026.x86_64-linux-musl-cxx03.tar.gz"
[[ImageMagick]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0b5c34642ae4c0454d817048bf9f7a08ac2271c5"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "d739801b2c25656b30c56c785fa0005bb83747f6386089c11d4afb51a8a5ee6a"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13026+0/ImageMagick.v6.9.13026.x86_64-linux-musl-cxx11.tar.gz"
[[ImageMagick]]
arch = "x86_64"
git-tree-sha1 = "9980d2badc74903f314da22ea07e06bcf8db8036"
os = "freebsd"

    [[ImageMagick.download]]
    sha256 = "4a8a10dc854a474c1622f2ee52d1d546ab2ba07129d7665ea407fff57ee62ad1"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13026+0/ImageMagick.v6.9.13026.x86_64-unknown-freebsd.tar.gz"
[[ImageMagick]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ebcbd437a23064fa08b9c29f6ec4855ac137101f"
os = "windows"

    [[ImageMagick.download]]
    sha256 = "e4b4922eaf873eb46b1945708ebe1dd45ab34ff2b1d5f942d49619d83843b156"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13026+0/ImageMagick.v6.9.13026.x86_64-w64-mingw32-cxx03.tar.gz"
[[ImageMagick]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "be08c9318d9919cdf76fa1dc519eed619d0e316a"
os = "windows"

    [[ImageMagick.download]]
    sha256 = "28cfbcce7f884fccd535a5bb5357a43919c1bd9a228d7fcf5631678dea1f82af"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13026+0/ImageMagick.v6.9.13026.x86_64-w64-mingw32-cxx11.tar.gz"
