[[ImageMagick]]
arch = "aarch64"
git-tree-sha1 = "af00cf61d7b4e0b584a8dabcd7ebe1c2f802bd59"
os = "macos"

    [[ImageMagick.download]]
    sha256 = "a74f04d55588ec9325f438cac9cde90bff3b067ce4cca6d6e772128cd8f86266"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v7.1.1+1/ImageMagick.v7.1.1.aarch64-apple-darwin.tar.gz"
[[ImageMagick]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8c9a4b8fb0daadbe82964cae6548f8e3d42c1e3e"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "d2f1256819040b1833a46af8b96508d287f2b965ae5854f1067f5edb109c1473"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v7.1.1+1/ImageMagick.v7.1.1.aarch64-linux-gnu-cxx03.tar.gz"
[[ImageMagick]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "39a7c315bda988a937230fbd0291e39a928a3364"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "8f5be0def63ffef273e5650737dde65e0e0cb4d9c75b827c26ac048ded0190a0"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v7.1.1+1/ImageMagick.v7.1.1.aarch64-linux-gnu-cxx11.tar.gz"
[[ImageMagick]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "da23abf0977cda3a355f3263c744b175e5006835"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "7ba5ed9cfd32bd5507eb1ed297ec7e94b722dfe5d4ccafaa44d8e7c6e374768f"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v7.1.1+1/ImageMagick.v7.1.1.aarch64-linux-musl-cxx03.tar.gz"
[[ImageMagick]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "81b3b339ced766856e10083badc6c05076b56b2f"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "36a70213c143f76c2173e274e9c22aa8a06e059ee8f236fef651cd770c5a2e42"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v7.1.1+1/ImageMagick.v7.1.1.aarch64-linux-musl-cxx11.tar.gz"
[[ImageMagick]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "eecc21a9aad5e9579d6e838fa6dd7be7b841d21c"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "698703a1a89fd5ef5bfdfc68a0ad00c2bca3812ab2738dba5062882bdc088ef4"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v7.1.1+1/ImageMagick.v7.1.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[ImageMagick]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "efa15089606c09bc3d664bfca114f0e51c7b154e"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "cf5fb02b873cc4e4f1fdb0b28c918a67919de1b67ba412addc09f5f6572d2d4d"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v7.1.1+1/ImageMagick.v7.1.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[ImageMagick]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f3db6307d59ef487acf4a4f9264b0689cfc349ce"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "e4ca8b957105e4505f5f6ae56c547a1034b33353729d17ef30e039eed628ea8c"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v7.1.1+1/ImageMagick.v7.1.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[ImageMagick]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e3d8538ffa5646b2ab599ff8bc50afcdf559354b"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "5d7146d6ad6428cfe8ab1201326dbdc75d2c6b03d4ae201debc6153b0055c782"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v7.1.1+1/ImageMagick.v7.1.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[ImageMagick]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3bb9b60a94bd9fcf72de8dd3cf5d82e8600cc9be"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "fe0260e6d66e4db0d606c6c95d038f24b58ac9642fc09ba0475aa5984a28f231"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v7.1.1+1/ImageMagick.v7.1.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[ImageMagick]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "17d5b7b5541e8df28e62f70708b9dd5289a0bc9f"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "a1b6de6823725631ba465b4c9b14fe555988166c641e73fffe918d12785c967d"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v7.1.1+1/ImageMagick.v7.1.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[ImageMagick]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7ca98c393d4f9cdd4ceecaf91c628f5ee116c124"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "c8d2817a7487bcbcfc53b0cbbf0c4a767f72735e431a346b4439b68e43db2b0e"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v7.1.1+1/ImageMagick.v7.1.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[ImageMagick]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b732b63955cc792e752103b8ef8edd5dbb9e933f"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "e3278ec11bde325516bfde74f76d3ddaaff3dc793f95267ada567191db2bf5ca"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v7.1.1+1/ImageMagick.v7.1.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[ImageMagick]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1ed1c655656b8020f378c840f38abecb4fc03868"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "8572227d7b999d2b0c0f6723971280ead15924b6a9ef610ace3be7b6728ccc7b"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v7.1.1+1/ImageMagick.v7.1.1.i686-linux-gnu-cxx03.tar.gz"
[[ImageMagick]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8b940df9fef5f8a652d92c89ae92169eae40b64d"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "622c5974ac945dea7e8e70e64f444a43460cff1fedf973222aefcf9e99559161"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v7.1.1+1/ImageMagick.v7.1.1.i686-linux-gnu-cxx11.tar.gz"
[[ImageMagick]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "012dbca0b1ef20666c43a7cc85b8504276c79e36"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "34331515c1be7851ee7347de53d8a1f0cc52d5e547c092601b1bb5c4eece58ef"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v7.1.1+1/ImageMagick.v7.1.1.i686-linux-musl-cxx03.tar.gz"
[[ImageMagick]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "31b69ee2a63729cd5a4ecddb143236c59d7fda49"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "073ce064b374c7ad39eca7f36fabc03a38c44928a488e407cf53f82d4df70bae"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v7.1.1+1/ImageMagick.v7.1.1.i686-linux-musl-cxx11.tar.gz"
[[ImageMagick]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b97d55907a3dd2e936115d43e40d4d23f7b2deb4"
os = "windows"

    [[ImageMagick.download]]
    sha256 = "6e47b8df825c3814ed7e54ad25ad8928afcbe5386ac2b08bf5f95272f2b96a1b"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v7.1.1+1/ImageMagick.v7.1.1.i686-w64-mingw32-cxx03.tar.gz"
[[ImageMagick]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "427544e6a8140161e26ae4104fd44e8b01a9e181"
os = "windows"

    [[ImageMagick.download]]
    sha256 = "58c72656fa1548f1cdd7881f3e49db344b25c3a241b3ba8b6dabc8bd4fc79925"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v7.1.1+1/ImageMagick.v7.1.1.i686-w64-mingw32-cxx11.tar.gz"
[[ImageMagick]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f1ccfed70c2c5fc598f9be7fdf4beeec598ff11d"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "d4064923ce0397341fff0c5e5ec5791c7de8f63c35b16687749cc97acd1eea3c"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v7.1.1+1/ImageMagick.v7.1.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[ImageMagick]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ee81bdad7f3ba825880adf69467d85aa76e54fe1"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "ea451e4e9ad6f49f8ee3d6612238d5d2d860720421ffd55d4d6c4693ac9d880e"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v7.1.1+1/ImageMagick.v7.1.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[ImageMagick]]
arch = "x86_64"
git-tree-sha1 = "a6575ff84f66a304b853ac9e532197a5b61ddc9c"
os = "macos"

    [[ImageMagick.download]]
    sha256 = "d57e9744cd5c2f4aeb2b34ae652294b56452356dd06a122be410765972d54db8"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v7.1.1+1/ImageMagick.v7.1.1.x86_64-apple-darwin.tar.gz"
[[ImageMagick]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2848fcd19a8cc22e3da68e637ee068feac4e9579"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "bc0e589c1ae55ff493417301e8f5c89175d85d936d839cf2746dc994aaad8ec5"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v7.1.1+1/ImageMagick.v7.1.1.x86_64-linux-gnu-cxx03.tar.gz"
[[ImageMagick]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "049f45ea8fb58e8e3a4bec857f50a240394776d3"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "b827f27c894cf301d4ecd42e3d0025ee5e3537867e6d76c9b06bb2cfcdae4eed"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v7.1.1+1/ImageMagick.v7.1.1.x86_64-linux-gnu-cxx11.tar.gz"
[[ImageMagick]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "33aa891863ed02fdda6874463c787fe0959b1e74"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "4ef8ad0d58ad7b4216c10035df5f8a59bfd2e42a9a627ef1257c5ae82504d8f1"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v7.1.1+1/ImageMagick.v7.1.1.x86_64-linux-musl-cxx03.tar.gz"
[[ImageMagick]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "55ea6c2809f97900178a5abe2f311c6766b064c2"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "4529cf94ad1d207766128e70092f28adb5b2cddbcfd6943403543db7e5166ae8"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v7.1.1+1/ImageMagick.v7.1.1.x86_64-linux-musl-cxx11.tar.gz"
[[ImageMagick]]
arch = "x86_64"
git-tree-sha1 = "2de37ffaa9ab9e9b193f3d145096dfd5ecd3df71"
os = "freebsd"

    [[ImageMagick.download]]
    sha256 = "da4961a958b26162fb06528caa00ab5c2a5d762e9e253eb296dc718ccebd669c"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v7.1.1+1/ImageMagick.v7.1.1.x86_64-unknown-freebsd.tar.gz"
[[ImageMagick]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "38a9d832c0fe72049c112cce692ec716e6ff6847"
os = "windows"

    [[ImageMagick.download]]
    sha256 = "e75fa23c364f9e994513f1c2b8f17b7cb680a7b0cbe699c815a04db814c4b391"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v7.1.1+1/ImageMagick.v7.1.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[ImageMagick]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6aa046ce994bd668eb1854adf2ab082f4ab474e3"
os = "windows"

    [[ImageMagick.download]]
    sha256 = "a16d1b8fa5b9214656e230d3e9418959f6c70b8dade85a5b02706a6d0bef7da4"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v7.1.1+1/ImageMagick.v7.1.1.x86_64-w64-mingw32-cxx11.tar.gz"
