[[ImageMagick]]
arch = "aarch64"
git-tree-sha1 = "c123990d1438130f712992a42c5413788948f10d"
os = "macos"

    [[ImageMagick.download]]
    sha256 = "29e2f666898a1295ebdc82e9c707aaf39819c53c82cf8efc693b63035ff46a76"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.12+4/ImageMagick.v6.9.12.aarch64-apple-darwin.tar.gz"
[[ImageMagick]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1243bffda5ebf48ef7378856e24f13ee743d12d6"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "a108a625fe7f5db1a6b91e49f02d8863c8b278914cf29e16c3579396c045d761"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.12+4/ImageMagick.v6.9.12.aarch64-linux-gnu-cxx03.tar.gz"
[[ImageMagick]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "133608a4f1796826335ba5d78791e687f3581dbe"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "f42072a3dc987741314d38a09afb933223457a09e9afa85659ba29b9f8177141"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.12+4/ImageMagick.v6.9.12.aarch64-linux-gnu-cxx11.tar.gz"
[[ImageMagick]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8234b91662f88961e30e37f3e95679bca57de3c0"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "109bdd3e2abfe9d6757cb7007907fdd25c326f0a120e05726bc19bb6ae3a7b29"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.12+4/ImageMagick.v6.9.12.aarch64-linux-musl-cxx03.tar.gz"
[[ImageMagick]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e6a810cd7ca68d2a53a35c28011e0095d78e5f83"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "1d4e99656a6fe2ee871d2e554f419ac93136e89fd5bae4ca95f0897c2f9d81d7"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.12+4/ImageMagick.v6.9.12.aarch64-linux-musl-cxx11.tar.gz"
[[ImageMagick]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2d594a7a7818ddad6d2deee780ffc3caa7b83f0d"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "7289edb21dbd79622b9285c62d0395dc0cd96ffa60f797de7afe8b34812d03d1"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.12+4/ImageMagick.v6.9.12.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[ImageMagick]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fe83d3a8cf8d6f8a0868fbe73ab72871890190a8"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "0e2e903a2175fe1f45e299e8c954129c7d6ceb3dcbde734d09be0681a4285d24"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.12+4/ImageMagick.v6.9.12.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[ImageMagick]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4f824d6059e0a737cde8f189b2c942226144f69c"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "47a2d2bc959b7937ef332588a562b31058deca07f3c4ee970a2bc34c85e83c03"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.12+4/ImageMagick.v6.9.12.armv6l-linux-musleabihf-cxx03.tar.gz"
[[ImageMagick]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b1c750389835982b2bc50c02f71a4d0360fb9bf8"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "89cc57dee82e84bb74d960c83d2c8b03a6574f189756d69770951d55bd896a34"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.12+4/ImageMagick.v6.9.12.armv6l-linux-musleabihf-cxx11.tar.gz"
[[ImageMagick]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9448b3ce34d195b11129a466996af998797a5030"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "19f538adf5c516a5feef55563072c732781de6821bb4cf940fdfff2eecf628e8"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.12+4/ImageMagick.v6.9.12.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[ImageMagick]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d6fb3c28bdcc8b19d6e72ab8fb871391be7220a3"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "c59f93b689876f3410a33f3cdfa6d30d473d3c73c1ad075d95449d47ac6199ff"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.12+4/ImageMagick.v6.9.12.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[ImageMagick]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "db18bf2f5361956fa68b0c2989b3cff8e27918f6"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "0d46f770c1e25791214065656c569cd72b383c9b4f87694ea2662c594356b1d6"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.12+4/ImageMagick.v6.9.12.armv7l-linux-musleabihf-cxx03.tar.gz"
[[ImageMagick]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c623a333d69884da236a89fa4a3f7436e0caa122"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "ed65d4fff87c69458ba7bf3ba43192d79705a8565d74041ac2f6f051f47bf649"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.12+4/ImageMagick.v6.9.12.armv7l-linux-musleabihf-cxx11.tar.gz"
[[ImageMagick]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b6546fa0556e06bd08f9cab6bc1a7fa4233c9aa7"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "efa5e990a1b81185d04cc9bffd54d08501725e9e7ac4e858035ee5c11537f23e"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.12+4/ImageMagick.v6.9.12.i686-linux-gnu-cxx03.tar.gz"
[[ImageMagick]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "16632aed33f604fae593e405e7779688c22f8aed"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "59c7c6d7b9891bc803d47dac20b9625c5f0050fcbeed440a79db3a041b83c86e"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.12+4/ImageMagick.v6.9.12.i686-linux-gnu-cxx11.tar.gz"
[[ImageMagick]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d1fe8b924f5e0d460fa29410950fcce8254131a3"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "c172a300e99c4a3b88345b2d936680cff476e93bafced826b372d7760cc3538a"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.12+4/ImageMagick.v6.9.12.i686-linux-musl-cxx03.tar.gz"
[[ImageMagick]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "36e3b726b633dacc4b99e7aa6e71938f7463b59f"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "c32a8fd87ea436404b52622f974b62fe805b4ed478db257fafbd97820c3c54a7"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.12+4/ImageMagick.v6.9.12.i686-linux-musl-cxx11.tar.gz"
[[ImageMagick]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1d33b5bd1ba358f9ba64c2580b3127ace29d58ac"
os = "windows"

    [[ImageMagick.download]]
    sha256 = "ae71af10b8dabb8b9b2179ee7e1a2ad96082c6cd059650dfecd53a365f7926df"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.12+4/ImageMagick.v6.9.12.i686-w64-mingw32-cxx03.tar.gz"
[[ImageMagick]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ed45dcd9170eef3cf6f23726f693f0ec6ee5144f"
os = "windows"

    [[ImageMagick.download]]
    sha256 = "9906493588b723eab1a3d3e18f8b2ba50bc99d011b4827aab927fa9d733dd77c"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.12+4/ImageMagick.v6.9.12.i686-w64-mingw32-cxx11.tar.gz"
[[ImageMagick]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "adbd92c8eb4564b8a1a48464da3488e918c23661"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "af39f879c58d309c35d1db0b2293f335b9b16850da7293731fca0608f931022b"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.12+4/ImageMagick.v6.9.12.powerpc64le-linux-gnu-cxx03.tar.gz"
[[ImageMagick]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6a34a35c89e44356787f0c62c5e364390ff0d037"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "26a7b6200e30a1822e3c7668ff36c153ed33045ecb6bbe403e84136f1c8d444b"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.12+4/ImageMagick.v6.9.12.powerpc64le-linux-gnu-cxx11.tar.gz"
[[ImageMagick]]
arch = "x86_64"
git-tree-sha1 = "ca3649104bb4add238b9f35ac5778f543a24b86e"
os = "macos"

    [[ImageMagick.download]]
    sha256 = "7afccbfb9fd91a8ff4d795c8d2af602e96301b79b33a63dfc71e5f4a493e4a89"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.12+4/ImageMagick.v6.9.12.x86_64-apple-darwin.tar.gz"
[[ImageMagick]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ebfb28a62c2bf7cc94ce08c12a1aac4d1a842ae3"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "befc7ce260a9e2c0f672764615493041fd78af1593cfa865360067301458ce38"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.12+4/ImageMagick.v6.9.12.x86_64-linux-gnu-cxx03.tar.gz"
[[ImageMagick]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b8e037624911b478e3bdb589c10c55af03f42481"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "0c05cf63609e2ee8bceb59bd89bb27f6078fafa5b5b6323287bfc01fb7f4ab14"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.12+4/ImageMagick.v6.9.12.x86_64-linux-gnu-cxx11.tar.gz"
[[ImageMagick]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8b2e73f718df63e74133741b85642fa3fe2990da"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "d962cb0be6f661bc356af6ae244c8e36f1d410afc63ffa476efb773481bf41a0"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.12+4/ImageMagick.v6.9.12.x86_64-linux-musl-cxx03.tar.gz"
[[ImageMagick]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3b9d5efc1de9ee44de8dbdef942673d21029246c"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "7e2495ec754371d93ab5f3442490f7b179327fc27742c8e257c700c057867b4d"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.12+4/ImageMagick.v6.9.12.x86_64-linux-musl-cxx11.tar.gz"
[[ImageMagick]]
arch = "x86_64"
git-tree-sha1 = "2fea0835d8d96fbfe1117c3b66943843f8f276da"
os = "freebsd"

    [[ImageMagick.download]]
    sha256 = "a38f635657f77f4af298d69cdebe265d63e05a8a43efc45e8067fe42d2f7b879"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.12+4/ImageMagick.v6.9.12.x86_64-unknown-freebsd.tar.gz"
[[ImageMagick]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "81492359639c008367003daba651bdb84b6f3e48"
os = "windows"

    [[ImageMagick.download]]
    sha256 = "db8a23eb2aa2cdf757689962ef9811ff9bdd57b1f505722ddc488e3a0e7ae32a"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.12+4/ImageMagick.v6.9.12.x86_64-w64-mingw32-cxx03.tar.gz"
[[ImageMagick]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b828a0bf39b5450e890fbf2f76c258e3db517110"
os = "windows"

    [[ImageMagick.download]]
    sha256 = "e398892cffe4cbcd0ceb936307ea57b1ae4847fe882e2ddd236febc301c1c2ec"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.12+4/ImageMagick.v6.9.12.x86_64-w64-mingw32-cxx11.tar.gz"
