[[ImageMagick]]
arch = "aarch64"
git-tree-sha1 = "15fd44839672e5713ca8b8a49047b7f8900890ed"
os = "macos"

    [[ImageMagick.download]]
    sha256 = "ee88be7e28b992ce9012e163939ccd0381cfca31269064e2708bfcecf2ee456d"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v7.1.1+2/ImageMagick.v7.1.1.aarch64-apple-darwin.tar.gz"
[[ImageMagick]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "91e6ae94a521db8bd26b06353a5119318a99395c"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "27171d0cb76ec03f1edcfa7594f5157cad2f812ae0e9910d7ae0f463c722566c"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v7.1.1+2/ImageMagick.v7.1.1.aarch64-linux-gnu-cxx03.tar.gz"
[[ImageMagick]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bee97793d31fb698ea06b0aea65d23328ebe61e9"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "5f2ab64d55810762dd69b41871349b5954481a41df53048190adbedc3cfb1de6"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v7.1.1+2/ImageMagick.v7.1.1.aarch64-linux-gnu-cxx11.tar.gz"
[[ImageMagick]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "684b9ce54fd744450c08ead6e6e57b5a97c6f568"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "2aeab16b8a3db5e671720ef443cf8765cfdb55ef5a0d711584814d189dd0e4b5"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v7.1.1+2/ImageMagick.v7.1.1.aarch64-linux-musl-cxx03.tar.gz"
[[ImageMagick]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "77834b427a38c2786a06889ad37a7cb0f219a570"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "e4208a2b637b9f138b771714bb7de2380b71f3c255bda526ce4cd3e29564af04"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v7.1.1+2/ImageMagick.v7.1.1.aarch64-linux-musl-cxx11.tar.gz"
[[ImageMagick]]
arch = "aarch64"
git-tree-sha1 = "a952d27cf58e426267bfbafa5f33c71c68cea155"
os = "freebsd"

    [[ImageMagick.download]]
    sha256 = "28f120ddbaa830327ffc5e6df6e7cddd33924caab29682ecdc63a92b22f3042c"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v7.1.1+2/ImageMagick.v7.1.1.aarch64-unknown-freebsd.tar.gz"
[[ImageMagick]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ab7924446bcbcb6d5cb49345fa732f21799fb9d7"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "bafdf5cb9191ab773f3585db8f4552fc79b475cafa2daa35b6eb11bf0198a749"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v7.1.1+2/ImageMagick.v7.1.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[ImageMagick]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e5493495c9c06bbbfaf51d82cc653f1ec1de9fc4"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "99c2f52118fd67d4cde8eff2374f1e46b44ecfc21610087d08e1e17ad0e03141"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v7.1.1+2/ImageMagick.v7.1.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[ImageMagick]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "facd4d0cb2bfbaa3ae6eaa309d99f656b5f614a6"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "35f0c9ac1317679da2d60af3054109e4218346933c6babc738e0fbbdfeead80b"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v7.1.1+2/ImageMagick.v7.1.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[ImageMagick]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c53cf9a7aebf92e953e075ce53bb1a5f420fc416"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "d8dbe673cb3be4ae0ec38ec5a1434f7ba022314c689fa20075fb1227fbff38c2"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v7.1.1+2/ImageMagick.v7.1.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[ImageMagick]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "baac26c84dfa20efd70dacc770da12afdb2acaa5"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "60e1678d032fd846eee8e95c8c4ad69e2f2b69ad0a3ea136b7d2956817a4ab68"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v7.1.1+2/ImageMagick.v7.1.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[ImageMagick]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9b2e1f212d1d516d2b32a69a21139eca422223be"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "b25830b0669b49e09394b382139d12ebf4f7128144b577b7dba9a2014d63489d"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v7.1.1+2/ImageMagick.v7.1.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[ImageMagick]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bc9faf0d2dfb73f8b8d5e6101428e61613268662"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "69c82087b78cf4b239efab861ed3082a7e07415a300fa655c76ba6dabcb7df99"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v7.1.1+2/ImageMagick.v7.1.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[ImageMagick]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c9c9e10b7298a0845b9c8b0f0ee32dddb2ca0541"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "1f4545300a9e7e2395b75a3cb4c492804b24c51370870d2d1f6a42a0baa3d080"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v7.1.1+2/ImageMagick.v7.1.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[ImageMagick]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "38f80370887bd5ff6ed627da2c90aff9442cbd7a"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "02bd104e97a42cc4e2620873a95f9d56eb2ef9471bb96ba0563bc318c0c8e585"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v7.1.1+2/ImageMagick.v7.1.1.i686-linux-gnu-cxx03.tar.gz"
[[ImageMagick]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f8dc611b89521e0b0f64820f59d78826eccb0672"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "c9b88baa13e35f5422ada7cbd39fd0b1358a72a0d7ea593446334fce88532869"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v7.1.1+2/ImageMagick.v7.1.1.i686-linux-gnu-cxx11.tar.gz"
[[ImageMagick]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2ae4885cffa1331ba9e2b426907ba8a3bf4fefbe"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "4263b580f4d0b17bfb5d6fa73b12534009e8c7398fe6fa6e7e7ea8c470ff53eb"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v7.1.1+2/ImageMagick.v7.1.1.i686-linux-musl-cxx03.tar.gz"
[[ImageMagick]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "320943f5b4f24815c83770e42fae0b0b0eb72a55"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "70368a343b95aba9dc944ddfa24cc4b76fcb10f46dc4d94208ea9f7372ccb3c5"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v7.1.1+2/ImageMagick.v7.1.1.i686-linux-musl-cxx11.tar.gz"
[[ImageMagick]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a95561dc79f58b53e881c408f371fa8c6fbd5cc5"
os = "windows"

    [[ImageMagick.download]]
    sha256 = "1b023f8dce44282abc7e6447e7c3ba89468b339065f6d8e92639001c8164ba41"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v7.1.1+2/ImageMagick.v7.1.1.i686-w64-mingw32-cxx03.tar.gz"
[[ImageMagick]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a209d1c7195c10cc5e738ff2552cc18e4d7bccbb"
os = "windows"

    [[ImageMagick.download]]
    sha256 = "c78e5aba6eb5b08af45bff91ce65c48737cf881b3b5857cf0417e94398124e15"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v7.1.1+2/ImageMagick.v7.1.1.i686-w64-mingw32-cxx11.tar.gz"
[[ImageMagick]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d9592591a6ab336160e5e32926cce7b129de7e8f"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "1e35c43b0a3035b182cb7ab638dec63d40f9142baed3d1ec35a8751dba241eb9"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v7.1.1+2/ImageMagick.v7.1.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[ImageMagick]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "783e826869a74d0625b160aec12a71d2c9d8cf5b"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "8d7b46e98b79e4db22f703e5b276a1af51a934ad5d3a49d6e564fef17087328e"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v7.1.1+2/ImageMagick.v7.1.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[ImageMagick]]
arch = "x86_64"
git-tree-sha1 = "998adf486009c9e1b40622ae1ef3dc73bf0e5473"
os = "macos"

    [[ImageMagick.download]]
    sha256 = "863d26985d4216136405a63ee8ad730e0d22f31e9f7db3c9b7a80df9fa7847cd"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v7.1.1+2/ImageMagick.v7.1.1.x86_64-apple-darwin.tar.gz"
[[ImageMagick]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "083ff093112d42c1fabf941c92b66199672e7c03"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "de4dcadddcad3634257827a99f215c478a474262c8c7a8bdc01f4aadfc780993"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v7.1.1+2/ImageMagick.v7.1.1.x86_64-linux-gnu-cxx03.tar.gz"
[[ImageMagick]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "210cf31fee34c5e7be7202d2d856566aebaca2fe"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "36637c172d48695c63c601553b6b2d3404858c0542690989b73cbb21f007b49b"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v7.1.1+2/ImageMagick.v7.1.1.x86_64-linux-gnu-cxx11.tar.gz"
[[ImageMagick]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ab3037703cae2f8ca1d6f84e8cf97d7d8c8982d7"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "4d305a46b25a72cd8b961883792b878ba845bae6158e24797e14db3fd3293d2c"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v7.1.1+2/ImageMagick.v7.1.1.x86_64-linux-musl-cxx03.tar.gz"
[[ImageMagick]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "75e3c150259d156a57a3ea45ff82c2293c9a92cd"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "3bb1ca575f286eca019d647718ae77a482a85c61536efdced125b3cadc14078a"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v7.1.1+2/ImageMagick.v7.1.1.x86_64-linux-musl-cxx11.tar.gz"
[[ImageMagick]]
arch = "x86_64"
git-tree-sha1 = "3025331732ae391d0f6822dd7ab3271997e60e3b"
os = "freebsd"

    [[ImageMagick.download]]
    sha256 = "e3712976b738d3748889f63a9dcde232ed2860ad97b06ba6ef941507b6be2519"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v7.1.1+2/ImageMagick.v7.1.1.x86_64-unknown-freebsd.tar.gz"
[[ImageMagick]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "95f01eec4e207776c29c78c4a37aad9e05d85da0"
os = "windows"

    [[ImageMagick.download]]
    sha256 = "86bdd461fcbe63e88a775088abf842b0e097c41c502a0bf3c6d3c389d831d456"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v7.1.1+2/ImageMagick.v7.1.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[ImageMagick]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5579b4ca9c77e5f05b4d2ce23fed7fde1cf66212"
os = "windows"

    [[ImageMagick.download]]
    sha256 = "6f1f23fa469867d182eaf73f7605aff9bd65d3477b138e8e73a73a833e7d5e27"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v7.1.1+2/ImageMagick.v7.1.1.x86_64-w64-mingw32-cxx11.tar.gz"
