[[ImageMagick]]
arch = "aarch64"
git-tree-sha1 = "52a01186642fe77e753588218309423a778613eb"
os = "macos"

    [[ImageMagick.download]]
    sha256 = "5c2925d4fb069d9d08ac1434af2e763a5183e2f3e013359c693884e4d9891480"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13+1/ImageMagick.v6.9.13.aarch64-apple-darwin.tar.gz"
[[ImageMagick]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "da637d2b6e95f67ae047cac0016b210c7f600261"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "d270f4a0229bef510f3649070062bc508324ba79e988165837f7a5b7cfd31399"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13+1/ImageMagick.v6.9.13.aarch64-linux-gnu-cxx03.tar.gz"
[[ImageMagick]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a52b72ba1d8db8830800bbdacd8dba5c5fb0a394"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "2e655d975e9c6ae26e9d20b4d52122b0c221927c52c746c1a0811ac1467937cf"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13+1/ImageMagick.v6.9.13.aarch64-linux-gnu-cxx11.tar.gz"
[[ImageMagick]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "34f4ba614664e93ea706211dc2ec839dfeb107b3"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "e4406e3839f5103716b730111f24cda70e7e800e956527c15df750178fcb2e14"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13+1/ImageMagick.v6.9.13.aarch64-linux-musl-cxx03.tar.gz"
[[ImageMagick]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2958116103b43ced62addc49521d114cd6a6bc19"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "5abcc7b841f6456f76b0dba953380702c95828bc1f1e4f841614165f6176a760"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13+1/ImageMagick.v6.9.13.aarch64-linux-musl-cxx11.tar.gz"
[[ImageMagick]]
arch = "aarch64"
git-tree-sha1 = "e767bc046a9c788fb8f45535657d7484fcce00a7"
os = "freebsd"

    [[ImageMagick.download]]
    sha256 = "44a413f349d2a8c02987c0f1b97b88e099c58337bfc6d184cf466eda66b5178a"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13+1/ImageMagick.v6.9.13.aarch64-unknown-freebsd.tar.gz"
[[ImageMagick]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "40c95c7118df527a1481f6e5e4195192e5d9adb1"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "00398de3446a8bc2208a1b7749ff680a59e1a314e7907c43ceb98e3e004923d6"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13+1/ImageMagick.v6.9.13.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[ImageMagick]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1efae96a8ea342c1bfe37258883370239c06158c"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "fc326efc76f3a0a272a589477378010282c3478554bc98e8dc20a9758c841d8d"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13+1/ImageMagick.v6.9.13.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[ImageMagick]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ce959b789d02360a36167e65e53578238a2d439c"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "a52a5c2f385b178a9c7dc380e9a288c5ebe33e7a34649063b2c4114b0f382fa4"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13+1/ImageMagick.v6.9.13.armv6l-linux-musleabihf-cxx03.tar.gz"
[[ImageMagick]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f2f757d1c1051943249f7f134feaa368f8741a03"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "c6f2215da13fd7c40f52b79632f06aa7e7b6755054ec6b319c4c0ecb9fa9cd7d"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13+1/ImageMagick.v6.9.13.armv6l-linux-musleabihf-cxx11.tar.gz"
[[ImageMagick]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "809f4e3a103fa2113a35610fe4d5be4b12c56e3f"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "565c55167794975808dda3835afb3e909e8c572f8934b63052ed1675978e7b96"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13+1/ImageMagick.v6.9.13.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[ImageMagick]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "985d37f5ae07cffa57210da0e875c54ec9657f70"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "714475c3060de24a54b2d4d608a3ad0ef40e24af86d0334e27188fb3f9a95d09"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13+1/ImageMagick.v6.9.13.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[ImageMagick]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "235c32d5dc97b8baf603a61380c59b1a7eacb1d9"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "8e81b644ddc0fc91ae3e411a51b52ce449d13c510860d0a01cc4299bf24861f7"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13+1/ImageMagick.v6.9.13.armv7l-linux-musleabihf-cxx03.tar.gz"
[[ImageMagick]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "55497b33c65660608e86b0f2a10c4c240024b51e"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "94de8dfe5d80a34770501bc5125f8baaa21583408955776a30330be161d4e54a"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13+1/ImageMagick.v6.9.13.armv7l-linux-musleabihf-cxx11.tar.gz"
[[ImageMagick]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dac705aaeb5b3445e092bed00a49773472c638b6"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "e7a8591f0c158c88e4ef4821b8b49b8b6181973ac8f4e63492d184d5f785a865"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13+1/ImageMagick.v6.9.13.i686-linux-gnu-cxx03.tar.gz"
[[ImageMagick]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6a18d45c5b2548837e8a91d97c9389fb809cb804"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "0f766d659ee5336ad3c79686c65dd269668ee43434ef094bf32758d9e7a679e2"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13+1/ImageMagick.v6.9.13.i686-linux-gnu-cxx11.tar.gz"
[[ImageMagick]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "95db5a72f273be861d78af4bb8ec20282ff4720d"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "ec3c86b311f4941d2e27cddac44740f7fbf26b36a9aec04e4081cfd3dbde8587"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13+1/ImageMagick.v6.9.13.i686-linux-musl-cxx03.tar.gz"
[[ImageMagick]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1d989fbca99e8e277de1ecc27797dcb4c67bf260"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "763cdb0b438f4dab2cfb73944ed319bdef7385c6b83f79d9b2fc32ae4b68dc18"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13+1/ImageMagick.v6.9.13.i686-linux-musl-cxx11.tar.gz"
[[ImageMagick]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "df813c26bd0576460d6ed75a0340ddbd1dca712a"
os = "windows"

    [[ImageMagick.download]]
    sha256 = "1efd14cfa55d2fc3cd3c71436983dada047ad143382438b7c9c1a996c7f7660d"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13+1/ImageMagick.v6.9.13.i686-w64-mingw32-cxx03.tar.gz"
[[ImageMagick]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "294b6ef788000076cdd182d98953b76f30c4ca88"
os = "windows"

    [[ImageMagick.download]]
    sha256 = "58d4906fbc33a41187f6088785aa5c5deec0a95c39aec216ef7e9ea1e5fc8381"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13+1/ImageMagick.v6.9.13.i686-w64-mingw32-cxx11.tar.gz"
[[ImageMagick]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9726f28f18e900d7214e2f68f8c6b69829e4eec2"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "d1ee3e2ece62f57cf63e67599cb06f04d051d8919ef5bdd61c4991715d3df679"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13+1/ImageMagick.v6.9.13.powerpc64le-linux-gnu-cxx03.tar.gz"
[[ImageMagick]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b700df892d07af06e0a27ea6102b3eb00317869d"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "ccbea3016f87a6518390c04edcb673898626fcb1cb4ad6a8e19ad741922b8486"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13+1/ImageMagick.v6.9.13.powerpc64le-linux-gnu-cxx11.tar.gz"
[[ImageMagick]]
arch = "x86_64"
git-tree-sha1 = "48989cedd4d6696aa143f0971d947f0c88cb0306"
os = "macos"

    [[ImageMagick.download]]
    sha256 = "09b22172c32ad7d0088d242d5876af86989a5629a23aebc73f283a75eb3bbbf4"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13+1/ImageMagick.v6.9.13.x86_64-apple-darwin.tar.gz"
[[ImageMagick]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1dbd83e51dbfac3f0c9d05cf3194ed5efebee781"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "884385dd5435e8efbd2a498311b18e9453630aebe24016297c5f6ac11f06728f"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13+1/ImageMagick.v6.9.13.x86_64-linux-gnu-cxx03.tar.gz"
[[ImageMagick]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "010b992421739625f2f8861eed8e8cf7c6004093"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "5038baf96ffcfa74d2f17e78d700619251317fa795ca2fb27f0aa739c7c3f82d"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13+1/ImageMagick.v6.9.13.x86_64-linux-gnu-cxx11.tar.gz"
[[ImageMagick]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "04b09349ac15a5cb17e1f23edc3040d28fdb7584"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "1e4e942e4b51ddc3d2e67af51c02901dc82d8142c014f7ee9872427529a07180"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13+1/ImageMagick.v6.9.13.x86_64-linux-musl-cxx03.tar.gz"
[[ImageMagick]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ede188eb49ae2b58913259d2bcdc1fd18029733b"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "0bba111780891810c4050e7fb2336e29617ea1b7e61aebab2aa9414db3bd17be"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13+1/ImageMagick.v6.9.13.x86_64-linux-musl-cxx11.tar.gz"
[[ImageMagick]]
arch = "x86_64"
git-tree-sha1 = "840b63c7a5e599f875b50be37bbbccc7ac64e23d"
os = "freebsd"

    [[ImageMagick.download]]
    sha256 = "873041505037af45d7de0b143db8694ba600b2159ff028aaf812c12fe20b36ab"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13+1/ImageMagick.v6.9.13.x86_64-unknown-freebsd.tar.gz"
[[ImageMagick]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "febc7628f8d3ee42d809c820b5e044b1753b9680"
os = "windows"

    [[ImageMagick.download]]
    sha256 = "4fe69c45f9038f2e59909c1b7ba97c9ce1aca08232f07f0ceecc5df71d3d4f82"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13+1/ImageMagick.v6.9.13.x86_64-w64-mingw32-cxx03.tar.gz"
[[ImageMagick]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bb2c931e0e440759c9121bdc93cb0003e64f31fc"
os = "windows"

    [[ImageMagick.download]]
    sha256 = "4c3e384d0d7f998ddae60b7f4399a3db9defb32fa18166ce5dce12ba4fb9b441"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13+1/ImageMagick.v6.9.13.x86_64-w64-mingw32-cxx11.tar.gz"
