[[ImageMagick]]
arch = "i686"
git-tree-sha1 = "8b2a3d10b6abcc6f8c19823d588e69262c3d5d27"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "193a815b8be7d6ea515885f65974e1135ce34fccc5a41ebe7a4c4fea391f0151"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.10-12+1/ImageMagick.v6.9.10-12.i686-linux-musl.tar.gz"
[[ImageMagick]]
arch = "aarch64"
git-tree-sha1 = "d4aee97aa17b38e11aa8d720c351a81d20372543"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "901d7dbb59e281f00056ca6040d8b4266048eb4b01e1cded1ef49bdb6e52b9d0"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.10-12+1/ImageMagick.v6.9.10-12.aarch64-linux-musl.tar.gz"
[[ImageMagick]]
arch = "i686"
git-tree-sha1 = "22ff8241a11b5bcd04b67a4518d8e270f924fbae"
os = "windows"

    [[ImageMagick.download]]
    sha256 = "0d8a876746a550fa2693fdfb17ec4c1d1f44aaa479ad86709f3184cef85b7873"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.10-12+1/ImageMagick.v6.9.10-12.i686-w64-mingw32.tar.gz"
[[ImageMagick]]
arch = "x86_64"
git-tree-sha1 = "2c8da4bd5da54111710ceb1b449b9899fa138c0b"
os = "windows"

    [[ImageMagick.download]]
    sha256 = "10ad38084cba2078b79c182b9846cd85179b86dd0016ad2725da98c3b8d7dd51"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.10-12+1/ImageMagick.v6.9.10-12.x86_64-w64-mingw32.tar.gz"
[[ImageMagick]]
arch = "armv7l"
git-tree-sha1 = "554788231ce776952cca6d8f6803a6dd9a1b6cca"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "224098fe51f067074c24bb6cc09efce89e8e8bdfb169dea935a3a127aefc05ad"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.10-12+1/ImageMagick.v6.9.10-12.armv7l-linux-gnueabihf.tar.gz"
[[ImageMagick]]
arch = "armv7l"
git-tree-sha1 = "53ea7c9cd97a1d4d8405185aae351ec0a6829fb1"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "557cc3ff57e2d09fe968ba953d391c7a879e9c8adcb7969a34a318a82caff7cb"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.10-12+1/ImageMagick.v6.9.10-12.armv7l-linux-musleabihf.tar.gz"
[[ImageMagick]]
arch = "i686"
git-tree-sha1 = "d7474a78a0f209243d1eb2db4cef523c9d81f0c0"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "656368221244cf64c08975a423301a770b7b418e637f22d9c82720b51493a26e"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.10-12+1/ImageMagick.v6.9.10-12.i686-linux-gnu.tar.gz"
[[ImageMagick]]
arch = "x86_64"
git-tree-sha1 = "a5d19e3682978a4b214a7d76415ca82cd948e2e9"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "83df983b1b9f63d832f480023934990e5171bba434d85495c04252b426c825b4"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.10-12+1/ImageMagick.v6.9.10-12.x86_64-linux-gnu.tar.gz"
[[ImageMagick]]
arch = "powerpc64le"
git-tree-sha1 = "80893cb760a9fc7cb41b4789ae93c661a9c20c44"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "227cf2b30098f6bf2f985547ff47f15db726cac00bda68220aa83557d99b74cd"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.10-12+1/ImageMagick.v6.9.10-12.powerpc64le-linux-gnu.tar.gz"
[[ImageMagick]]
arch = "x86_64"
git-tree-sha1 = "6cf40347c2068d2a0e7b1a26b19ba904bcc53def"
os = "macos"

    [[ImageMagick.download]]
    sha256 = "7046077393c9921b2a70911fe02fb1bcd150fc07d3352ec176e96d2ea57b92ca"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.10-12+1/ImageMagick.v6.9.10-12.x86_64-apple-darwin14.tar.gz"
[[ImageMagick]]
arch = "aarch64"
git-tree-sha1 = "2e3c78cf1568f1e07f3648c164e0472b3da47cd1"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "1cff8ee1e628e8a6765275d10a01699a264f7e5df3ff6433edd02d231349a012"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.10-12+1/ImageMagick.v6.9.10-12.aarch64-linux-gnu.tar.gz"
[[ImageMagick]]
arch = "x86_64"
git-tree-sha1 = "7cefbcd2e337d8eb4600f6a9e654d952bb8be410"
os = "freebsd"

    [[ImageMagick.download]]
    sha256 = "7a6a80e59429bb349398b67511d949a1c85db1f9a77d2e731a6bc98e14c90bca"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.10-12+1/ImageMagick.v6.9.10-12.x86_64-unknown-freebsd11.1.tar.gz"
[[ImageMagick]]
arch = "x86_64"
git-tree-sha1 = "747ad7511ebe63900cbba42cadb33b75222efbef"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "45a57d78b29de305bc1ab199a359bf94fb8ee1ba37f42ad351182e692c7f9354"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.10-12+1/ImageMagick.v6.9.10-12.x86_64-linux-musl.tar.gz"
