[[ImageMagick]]
arch = "aarch64"
git-tree-sha1 = "a284f49eac5c6411db751f9ad004dde5ee869bb3"
os = "macos"

    [[ImageMagick.download]]
    sha256 = "b6585b0bd93072da742f1082441db68b251f8ab62ef1a7b61300d7c938da9ecd"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13025+0/ImageMagick.v6.9.13025.aarch64-apple-darwin.tar.gz"
[[ImageMagick]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "48bb671069853d06e71aae2dcab4770884b68cbd"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "87c0a589b2cdac14ca1c57f479163f5c9f2ffbdf22e0572af2c2147d0ee5d5ed"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13025+0/ImageMagick.v6.9.13025.aarch64-linux-gnu-cxx03.tar.gz"
[[ImageMagick]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "44d015472cf1e6d5b430b9b45d3562bc9a72a850"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "fae5ce6118df2411864e307d46ba8478464b0a3edefee45ae3d23b0d5572af69"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13025+0/ImageMagick.v6.9.13025.aarch64-linux-gnu-cxx11.tar.gz"
[[ImageMagick]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c45f7e11d66dd95bb86120415bf832496e17bc1a"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "6a6fe2fcfa06cbfebd45259c906ef098e29857305674a5f825183e94be5fa109"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13025+0/ImageMagick.v6.9.13025.aarch64-linux-musl-cxx03.tar.gz"
[[ImageMagick]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "71207bb2eff7ccdd68f37ac6319edde937236d31"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "4e1e6ea9bf484b61fcbe7c5863b249e3434d4f1afe57ae6bd62b10bcae57944e"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13025+0/ImageMagick.v6.9.13025.aarch64-linux-musl-cxx11.tar.gz"
[[ImageMagick]]
arch = "aarch64"
git-tree-sha1 = "53265ff624c10cf8aa9de1bd4964b5ff030d07fa"
os = "freebsd"

    [[ImageMagick.download]]
    sha256 = "14e72b75bae9ffe45bc1ecd6e2a016225b593e813b26b2f91463432f67269028"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13025+0/ImageMagick.v6.9.13025.aarch64-unknown-freebsd.tar.gz"
[[ImageMagick]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e06f8e0e041fa1e399282ac77cc1e65ca73346f6"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "24bbe5d7adc1fb9a8b5d7a65bdd6731b164fc1350aaff3a1011d1e3d515dd139"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13025+0/ImageMagick.v6.9.13025.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[ImageMagick]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6a94148780ce75afce806f9bafd37cc23efa54d7"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "a4899006c7498fa95f4e0bab72bc3d40ed6d943e2ec9014e3ba0edbfd74a275d"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13025+0/ImageMagick.v6.9.13025.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[ImageMagick]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0977312c143b44e18078d6419a6c2a897c7aabe6"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "ee0d43be7d58e76bf209e7da1e0db474a06d72dd42c67e838790742fc55cc45a"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13025+0/ImageMagick.v6.9.13025.armv6l-linux-musleabihf-cxx03.tar.gz"
[[ImageMagick]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1d30d6fcb8e5d1993bf22065f7da5ff7702eb9c9"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "c722ef00c3981f8c20c190cc7ef1e77f00549ede89db09df953ad5c0945822d2"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13025+0/ImageMagick.v6.9.13025.armv6l-linux-musleabihf-cxx11.tar.gz"
[[ImageMagick]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "12bb02ba9e2f184b893ad29e8b20bc4745b1335d"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "5ae47f4f15319ebcb28ea1a75b41e5233004613d13116c5a6efbb36ede249066"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13025+0/ImageMagick.v6.9.13025.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[ImageMagick]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d1cc53d9e39aec16994c7a6b74a2d51b337fb4bf"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "6c95924610aef29ba0b90b6bfc14bc3bcabd97a6af7bf7cda7a172a7f59dda0f"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13025+0/ImageMagick.v6.9.13025.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[ImageMagick]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "763ec116c9eb7efd5859c64b0c0effe1843c43df"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "da2629b4dcaef41000e566ccaa483f51d21ec35254a961613db2caebbba909fd"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13025+0/ImageMagick.v6.9.13025.armv7l-linux-musleabihf-cxx03.tar.gz"
[[ImageMagick]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "798ace0852344ea172cba3257a65cb090c8f256f"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "87df9c9229ac177c2361092b96c62569db7de714984bc4dbf0343c81fa538a43"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13025+0/ImageMagick.v6.9.13025.armv7l-linux-musleabihf-cxx11.tar.gz"
[[ImageMagick]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b50062bafd77c3be5c9a1f5bdb882d486be0a56a"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "f366ab2c46306e002a09f6390328d99d3eff5fe2693e1159e32ff8a704129536"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13025+0/ImageMagick.v6.9.13025.i686-linux-gnu-cxx03.tar.gz"
[[ImageMagick]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6777078cd54ba97d4dc5dd78f8129fd877520512"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "0b70424c2063191761b92ee784bb60b0ee90d073921052468ff14b3ea2208162"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13025+0/ImageMagick.v6.9.13025.i686-linux-gnu-cxx11.tar.gz"
[[ImageMagick]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "548f7292e3fe9364e2a39c0c424734dbd5fbadbb"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "dcac492f4c33bbf646a1ef9f0883e4bec6aa8d259394ee3edc37ee06904bf071"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13025+0/ImageMagick.v6.9.13025.i686-linux-musl-cxx03.tar.gz"
[[ImageMagick]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d2c2b411a31bd7a4d95cf0b58217c0bddafd25c4"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "d635ee95c1deb8f46ac2b71f3dc30ee9872298bf363dfea59361e10de0c0e90f"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13025+0/ImageMagick.v6.9.13025.i686-linux-musl-cxx11.tar.gz"
[[ImageMagick]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9da4580d1bd70a5115fdd90616e4418b128094ea"
os = "windows"

    [[ImageMagick.download]]
    sha256 = "e232beb5bc2a07c15854ebba77867ac08bd9e996e0a72fd78f07a7ff2c8d6ce3"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13025+0/ImageMagick.v6.9.13025.i686-w64-mingw32-cxx03.tar.gz"
[[ImageMagick]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "db5f6badad16ace6c894df571f238662e64fd104"
os = "windows"

    [[ImageMagick.download]]
    sha256 = "6f9b7e0f2f65c67ab4c1da77fdc588675d010f992f240475ae29a00feed7f598"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13025+0/ImageMagick.v6.9.13025.i686-w64-mingw32-cxx11.tar.gz"
[[ImageMagick]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f70bebc7dfcfe69b07ce767ff083e9a2dfd98417"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "20d05059d3f786df2a2c2fd204b7bc9e47527a5aab29bc6a9c7ce2e85e204e27"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13025+0/ImageMagick.v6.9.13025.powerpc64le-linux-gnu-cxx03.tar.gz"
[[ImageMagick]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6eb13030c4b21f4ddaf618657b05d0eb54e2b182"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "a895abc1434409797a7c2ef8125d9e0ead596aaf30e4e6798526905291036319"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13025+0/ImageMagick.v6.9.13025.powerpc64le-linux-gnu-cxx11.tar.gz"
[[ImageMagick]]
arch = "riscv64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9c96b0dece9ad85748221d518505d5788b23ea5d"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "4640f6e7149e6998a3371380e3032d74e92767de4202c2ef511bc7f671225177"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13025+0/ImageMagick.v6.9.13025.riscv64-linux-gnu-cxx03.tar.gz"
[[ImageMagick]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "78b2464ec3922ab77bb202d8a3f137806d9e6c9d"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "f96cf62b1852f434f2449eb4c9d9a8b57b3be45453b3bc1fc631a3cef901015e"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13025+0/ImageMagick.v6.9.13025.riscv64-linux-gnu-cxx11.tar.gz"
[[ImageMagick]]
arch = "x86_64"
git-tree-sha1 = "7b417506cbbffe1763c4f127ccf6a8ee103ec01d"
os = "macos"

    [[ImageMagick.download]]
    sha256 = "7b30c9e906f88d7ecee07206b173ed8161d2db9280b0033a5045193539316a7a"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13025+0/ImageMagick.v6.9.13025.x86_64-apple-darwin.tar.gz"
[[ImageMagick]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a660f23d3267103c3e6a39abad4ce784f1f0d292"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "71cdb4448c193799619c842f6ed0da0552453815d3c520e03eacf6816cc38695"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13025+0/ImageMagick.v6.9.13025.x86_64-linux-gnu-cxx03.tar.gz"
[[ImageMagick]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "890689b72fc110b31f912829465f3ef6f6be7204"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "332f910fb3ff6c9fdcfb878147d6095f665949b29f360c6a30f466c6ba7c56c1"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13025+0/ImageMagick.v6.9.13025.x86_64-linux-gnu-cxx11.tar.gz"
[[ImageMagick]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7e0bf727a9bd461892f8e1ab360dc68059ca6e70"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "b4054c7542bb3ec007542fcc3f5f3d3c817900c492d5d9a2f1f678f973e78e7b"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13025+0/ImageMagick.v6.9.13025.x86_64-linux-musl-cxx03.tar.gz"
[[ImageMagick]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "950fb9526af77c6724a30c9e3f57f45d631f356a"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "ebbd2da18c62fb8e5cbe5bd2cbdad5be5c32323e621deb4fa3d0e9cfecfabd36"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13025+0/ImageMagick.v6.9.13025.x86_64-linux-musl-cxx11.tar.gz"
[[ImageMagick]]
arch = "x86_64"
git-tree-sha1 = "5f3c17d52a6a433367982f0ddae38b6623417368"
os = "freebsd"

    [[ImageMagick.download]]
    sha256 = "d2f0f394fbbf754698010eb33834df57b0e5a16b42cae5aade1d9fb1a2ac7eba"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13025+0/ImageMagick.v6.9.13025.x86_64-unknown-freebsd.tar.gz"
[[ImageMagick]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9bc5dffaaff75a95a912fc61ea53acf72b851e80"
os = "windows"

    [[ImageMagick.download]]
    sha256 = "34451c794f682405f4f8b10aca4747bf3e0bd75e7a6925a9fcd782c1c75a1a63"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13025+0/ImageMagick.v6.9.13025.x86_64-w64-mingw32-cxx03.tar.gz"
[[ImageMagick]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "07981a40130a65aa9cea90e67c08002db6079b93"
os = "windows"

    [[ImageMagick.download]]
    sha256 = "55066ab73573812d2b2383cdefb271aec2dd4c6159a356ad71980b1b5a61f112"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13025+0/ImageMagick.v6.9.13025.x86_64-w64-mingw32-cxx11.tar.gz"
