[[ImageMagick]]
arch = "aarch64"
git-tree-sha1 = "4ef24e7e54c0aec8a582df3b0596446f12d17a27"
os = "macos"

    [[ImageMagick.download]]
    sha256 = "1c3ea098d3b139d8b233121956517231d76e00f39b974014142da350e0b12fcd"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.11+3/ImageMagick.v6.9.11.aarch64-apple-darwin.tar.gz"
[[ImageMagick]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c363166690de93cce3a66a9c059f8c9c37ed989a"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "f183b19234f952e3d31b7dfe7095cdbdfac3dfbe13109d336389213c34384372"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.11+3/ImageMagick.v6.9.11.aarch64-linux-gnu-cxx03.tar.gz"
[[ImageMagick]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9e8009d51705703821f23c412e09a97385ed20f8"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "b9cd173d4d7a2e08c7ea21dc18b4da414dee957f8f26871ccdaad9d34b69e765"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.11+3/ImageMagick.v6.9.11.aarch64-linux-gnu-cxx11.tar.gz"
[[ImageMagick]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "85130edf7ca71daa7fc481f1cc419d5b19fe74ce"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "6bf59b0326a4c5214a8da51d7630d285df89fe666e05ab5a480b6638883bc818"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.11+3/ImageMagick.v6.9.11.aarch64-linux-musl-cxx03.tar.gz"
[[ImageMagick]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a8b36425ac22f68594cbd364e3649b623f991c35"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "9c8e90e22295dbdd8b8e1d5d7dd59a4cb1c740f0ae3b730b7f4177baca4f26aa"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.11+3/ImageMagick.v6.9.11.aarch64-linux-musl-cxx11.tar.gz"
[[ImageMagick]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0a669bc0a87dcbe391508af8bd144a0e0c7c3326"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "8f4d22b3c0e841f2e6fa4288311b420bee2ed388998899b1971bde0bbe9cdc4e"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.11+3/ImageMagick.v6.9.11.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[ImageMagick]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "932018e10d75983144325713cb7f69cf0089f7a8"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "b06ba447d1b756b4708c8f41483cb00d3bb729b6b44ec804b94cd874d9ae3b05"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.11+3/ImageMagick.v6.9.11.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[ImageMagick]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f3be22b679bd1469c97a25705ebc3d985f8349f3"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "197a61a03e0edcc8bc6eff55084b594e4bf109f3decc846aaef41b529e9e4548"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.11+3/ImageMagick.v6.9.11.armv6l-linux-musleabihf-cxx03.tar.gz"
[[ImageMagick]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0938f64448d75e3c2f734c016336fcb7b55b1445"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "e54e21e12e8fa98671338bdb2f3a938f410c1c0c91a19b47fc01e40704241fb8"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.11+3/ImageMagick.v6.9.11.armv6l-linux-musleabihf-cxx11.tar.gz"
[[ImageMagick]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6fddf6c5eefeea16030a3f22702f0e6f979a20f9"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "e5d18c2e8e89f6f73627f2986e810b0193abc642c7ef073a56aa41a5178de651"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.11+3/ImageMagick.v6.9.11.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[ImageMagick]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d206156fbb1ca5d5dbf0e9079e00fb17c540d569"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "82fb622d5fb3d30ed0edae97919dac633f5ce64299b5f9b5528f2c2b1e64764b"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.11+3/ImageMagick.v6.9.11.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[ImageMagick]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "57b017367a0cb660c498bf79974f62b92e414d57"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "06cf5e1f1a2bca01243bf5359247a93b980346e363c8a1e06938920419a03a53"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.11+3/ImageMagick.v6.9.11.armv7l-linux-musleabihf-cxx03.tar.gz"
[[ImageMagick]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3567fed90b6a0f1df4bc45c74454833506c0cd58"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "9908a130388f818a0539652a99f389e9d116e9c5ea1601ee80582fb1388372be"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.11+3/ImageMagick.v6.9.11.armv7l-linux-musleabihf-cxx11.tar.gz"
[[ImageMagick]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8a9a7d05b2de67b5cbb2947b76afbdc495e89d20"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "12d7285b984dccb37b3378c14696f4faeb809dd00b7881779265d712368ee20a"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.11+3/ImageMagick.v6.9.11.i686-linux-gnu-cxx03.tar.gz"
[[ImageMagick]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6f7e9bfdfc9d6a59b778893cdafc7853853ad1f8"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "5f3a4aec43d29ddd8234868a9aa6af50b099917e64d629f25fa71adcdd6d0918"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.11+3/ImageMagick.v6.9.11.i686-linux-gnu-cxx11.tar.gz"
[[ImageMagick]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "66969d9d7bb2d9c30bfb6f8d2069df849debda17"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "9d24505ed294e53a5cc0d42b73a82e913d9101bd21cfaafffb6738de3aa714bc"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.11+3/ImageMagick.v6.9.11.i686-linux-musl-cxx03.tar.gz"
[[ImageMagick]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "59b522f5d5d559414f12a16d79a5354e43cbe136"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "e2956754c30d22bce349cf6f65aff95427764ba85546014c82cee0fde964e429"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.11+3/ImageMagick.v6.9.11.i686-linux-musl-cxx11.tar.gz"
[[ImageMagick]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "267063e9c5dcb16e7e94c64cc1f151e7c6214624"
os = "windows"

    [[ImageMagick.download]]
    sha256 = "32c6ec5428855451fd68b35a13c4e3f583a8073ba5d139f3dccd5b29beef39f1"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.11+3/ImageMagick.v6.9.11.i686-w64-mingw32-cxx03.tar.gz"
[[ImageMagick]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bbd56d48368e8c8990b7a69832f1e3e7489e6f39"
os = "windows"

    [[ImageMagick.download]]
    sha256 = "358638fc7276ce22ac490fce09c98550eceb741b25c92918f998b3c29fb2a311"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.11+3/ImageMagick.v6.9.11.i686-w64-mingw32-cxx11.tar.gz"
[[ImageMagick]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7b077557168f7d55723d85b4a8c4e924184297d8"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "206cfe8b39c42857309797bf5ed5e1823032ec32a8e2657ef932f55089bdd891"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.11+3/ImageMagick.v6.9.11.powerpc64le-linux-gnu-cxx03.tar.gz"
[[ImageMagick]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3dda8003bc70e5350e272f4dc2fc746a4c36bced"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "321273a7d413991b6582c8327b206fbea02134468776d76eb356d4b3b05de028"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.11+3/ImageMagick.v6.9.11.powerpc64le-linux-gnu-cxx11.tar.gz"
[[ImageMagick]]
arch = "x86_64"
git-tree-sha1 = "ca34594646b2a8399911402072b6112cddbb8bea"
os = "macos"

    [[ImageMagick.download]]
    sha256 = "b530e0a6b8c6bd96f1f6101882dd36aa8141fadb8b407ff5c9d4b3d3d4484b40"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.11+3/ImageMagick.v6.9.11.x86_64-apple-darwin.tar.gz"
[[ImageMagick]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ce29bb870487cd7e4395c47b1483fdc560a15052"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "dc37ee122c74c65fc3abbcc129f3466b1d95e8c1df303d84de1f2371310108e3"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.11+3/ImageMagick.v6.9.11.x86_64-linux-gnu-cxx03.tar.gz"
[[ImageMagick]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e2b9478d7dc1ac875a2853edfa32df5fd267bc29"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "31137dd709526eb020c6123867bae066e531fc8e9e2928b6e81bb03f350bcb26"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.11+3/ImageMagick.v6.9.11.x86_64-linux-gnu-cxx11.tar.gz"
[[ImageMagick]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "80bcee80dfbe5bf935f753354b17d15ee68b7a6d"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "bcda7e1aa489d15251d090812558ca683d4ce9d926b6b118ee4526ced7de0e24"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.11+3/ImageMagick.v6.9.11.x86_64-linux-musl-cxx03.tar.gz"
[[ImageMagick]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "310149cba0e10577cdb951d1213ea06ff63f6d3c"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "bcc8b7ab454b35a0fa0f22c98cd4760556064ae8414ebfb269a5ecb49f9cb3de"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.11+3/ImageMagick.v6.9.11.x86_64-linux-musl-cxx11.tar.gz"
[[ImageMagick]]
arch = "x86_64"
git-tree-sha1 = "3ddbddf2b54f456d8e24216a9dd7210766a5eaae"
os = "freebsd"

    [[ImageMagick.download]]
    sha256 = "6ac57ed477dd27cb5472bd56cdb2b6615e3640e8258a83ec4ef3ad7dc48f088b"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.11+3/ImageMagick.v6.9.11.x86_64-unknown-freebsd.tar.gz"
[[ImageMagick]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6b922fd0bdbe125a8460ddcf3287a1c9b5513a62"
os = "windows"

    [[ImageMagick.download]]
    sha256 = "355d758a788635dfc6c387b85eaab1f2bde14fc75f840692ef84e03a624f2d4d"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.11+3/ImageMagick.v6.9.11.x86_64-w64-mingw32-cxx03.tar.gz"
[[ImageMagick]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ea464a378beb6bebfdcd04e767ef69c382c1190d"
os = "windows"

    [[ImageMagick.download]]
    sha256 = "9bbdfaeebc581960f152e263bbd2c7f951770d98aa2d1c2abcaa4a8bf30979ae"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.11+3/ImageMagick.v6.9.11.x86_64-w64-mingw32-cxx11.tar.gz"
