[[ImageMagick]]
arch = "aarch64"
git-tree-sha1 = "06f4db06426d5822bc8cc48cfdd494b4cb32366b"
os = "macos"

    [[ImageMagick.download]]
    sha256 = "b22c73208cd3b1e0e972d9a590b64e9494b5a13d92b0475836f3d41189365e70"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13+1/ImageMagick.v6.9.13.aarch64-apple-darwin.tar.gz"
[[ImageMagick]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5ea5270a407f3184a281547a175ed8f84b55aff1"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "b01a8a2b88f6b4dbbb27bec3a6964dadd48c6c66266cb97f6ea48de4eca804b9"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13+1/ImageMagick.v6.9.13.aarch64-linux-gnu-cxx03.tar.gz"
[[ImageMagick]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "81803d101f64eca8104bf9636da030a3198c68f5"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "0870568538ce5428db398129f914f3f71c918475a10fe6e4440ee9e30f71ef8d"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13+1/ImageMagick.v6.9.13.aarch64-linux-gnu-cxx11.tar.gz"
[[ImageMagick]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9dab256349e03e53968608510fc82f57ec04c3c7"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "29d337cb86daeb5853a600088143940e021d1124055af40254ed5f6aa56f4b51"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13+1/ImageMagick.v6.9.13.aarch64-linux-musl-cxx03.tar.gz"
[[ImageMagick]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fa2f9f29978188ab59ce42b19e6083eb1ecc560f"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "ff7b87734a5b8bff3f2e3b24090b1e4185922c54a3371e1c68f9f00d973a1aa9"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13+1/ImageMagick.v6.9.13.aarch64-linux-musl-cxx11.tar.gz"
[[ImageMagick]]
arch = "aarch64"
git-tree-sha1 = "9577e9020ddf617849ba2c1c60c8e2a55392b4ce"
os = "freebsd"

    [[ImageMagick.download]]
    sha256 = "d60dc740a17adced130c7ccbe5ce2571edd2aad32d1b797ecc3fbce55ca40f69"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13+1/ImageMagick.v6.9.13.aarch64-unknown-freebsd.tar.gz"
[[ImageMagick]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b510b2f7466bcb41b2b78100085e68eb2b88e349"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "5cd0fca6cc5639555560007a4c614d01ed077a4d52437e5d2b7fcd82360976cd"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13+1/ImageMagick.v6.9.13.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[ImageMagick]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "de76eb8dcb22b6dcc60033ea75a32df6c9e0b024"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "52600568953d27c7162c08737a7edd794f1117a9d088511351baed721ad0ec42"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13+1/ImageMagick.v6.9.13.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[ImageMagick]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "70f3fbd13c45d0d3e9a67f4cbf625cbc3d2f09d6"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "7868e0550db309e08c0eee5a503cb7a50e859eda3fea4edb316972e7795d7fbd"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13+1/ImageMagick.v6.9.13.armv6l-linux-musleabihf-cxx03.tar.gz"
[[ImageMagick]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c06c97c6881da5a627ef4b38df8e67ac57c61683"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "456fac99b0b4f4bf02d4f26f8f7190705561da1dacd899299818db607a87dd15"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13+1/ImageMagick.v6.9.13.armv6l-linux-musleabihf-cxx11.tar.gz"
[[ImageMagick]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ee00e24c06a569dcba01e8d2d1f8c5d1fe840f11"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "305b01933b588dc91427622caff80489e51d4d9253c52e14f00fc2a73151f2df"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13+1/ImageMagick.v6.9.13.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[ImageMagick]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1c59dabd98b1c1c63032da411dbc3e8325fd73ff"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "36fb5ec518ec258f6fa4fe70437038b547cac02f85a65c3b0acdd1a42b667113"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13+1/ImageMagick.v6.9.13.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[ImageMagick]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b473054ac61baf9343630d5c5804f3e1327923b2"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "63a4dbcb7a08495e115188aa234a22b47d0a11f2fcf2ee2422e4d8819613a2c0"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13+1/ImageMagick.v6.9.13.armv7l-linux-musleabihf-cxx03.tar.gz"
[[ImageMagick]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "743b082b5a04d107a8fdad2ec7fe9b734346b4bd"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "6ce4575d26dd64f0a9d41a5f767e83ff9a61ccaf23c69169c39f27bf4f8e5b80"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13+1/ImageMagick.v6.9.13.armv7l-linux-musleabihf-cxx11.tar.gz"
[[ImageMagick]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1502b2953f7051ef0fdae079333bb81a78370599"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "18ec170a67d1f7c7fa46ea56c6e466bd1c3ccfce010a1f86d7262ab0583c6f5e"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13+1/ImageMagick.v6.9.13.i686-linux-gnu-cxx03.tar.gz"
[[ImageMagick]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "834aaf31c389ee87412fb578216abb82e1f63beb"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "36d7a95d6335b4d648fdeb99fc49be195042877d4b542bc59338f8b4a535797e"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13+1/ImageMagick.v6.9.13.i686-linux-gnu-cxx11.tar.gz"
[[ImageMagick]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "26540ca9373ffbd661d3a783feaab63abb1275b2"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "b8ff5af2d9ae7deb72e203da5f4280d78c6afe2f299b3336f33f0f4ee708e436"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13+1/ImageMagick.v6.9.13.i686-linux-musl-cxx03.tar.gz"
[[ImageMagick]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3eb1c44ab6a4a69ec2a52820d88f31c45db15353"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "2873d913f1f89748fd636646f7e82059c81093a09f3b4846985aa0a1ffd2b7d6"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13+1/ImageMagick.v6.9.13.i686-linux-musl-cxx11.tar.gz"
[[ImageMagick]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "18e5bc455a82284b7d2a4004d13a0a30c2abaa17"
os = "windows"

    [[ImageMagick.download]]
    sha256 = "1fe7afda5e7d4de7e1931dacfaa7371e698f72beda00e79aaf852fbad32aea90"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13+1/ImageMagick.v6.9.13.i686-w64-mingw32-cxx03.tar.gz"
[[ImageMagick]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5577e6db68f17505f71e11c45c8a583a54c8164b"
os = "windows"

    [[ImageMagick.download]]
    sha256 = "be4f240848caa3c3ae8a7ae70e164341b24aec6bf40a01283a85bd55332180aa"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13+1/ImageMagick.v6.9.13.i686-w64-mingw32-cxx11.tar.gz"
[[ImageMagick]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cbdec9c55c662e67bfaf32e4b163edf29aedf73c"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "7d10deb98f397b26f98d6a7d3185e45c590d68fea6bc8feee12e401fe20f8c5d"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13+1/ImageMagick.v6.9.13.powerpc64le-linux-gnu-cxx03.tar.gz"
[[ImageMagick]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e39193be329cbbd6d7bf5aee9ac507c295b63db1"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "55f03c681ded7cf5ed4cb8d55c16f7fbb95f06a6c15893db5565ae17ced7603b"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13+1/ImageMagick.v6.9.13.powerpc64le-linux-gnu-cxx11.tar.gz"
[[ImageMagick]]
arch = "riscv64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "28acd38add012817d9495b5523314ce1a590391c"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "2e580e56abd9a7344906f239a4cd6d3d2ad6cd4ae37809fc2c8d3ffaf7d8d642"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13+1/ImageMagick.v6.9.13.riscv64-linux-gnu-cxx03.tar.gz"
[[ImageMagick]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4acd31d4fe9e177284789f5f42e7f4958adc6f63"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "5ef8bc73903f682ae78b8ccd11e39d92cac57a2f5677348b87c921ba974b00cd"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13+1/ImageMagick.v6.9.13.riscv64-linux-gnu-cxx11.tar.gz"
[[ImageMagick]]
arch = "x86_64"
git-tree-sha1 = "d339acf80774aef9778b350f9aa3a2e180110891"
os = "macos"

    [[ImageMagick.download]]
    sha256 = "14425d4f4ee59077633406f0f080d15cbf7f5aa7e2fc1a582eee918721ff931c"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13+1/ImageMagick.v6.9.13.x86_64-apple-darwin.tar.gz"
[[ImageMagick]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c4cd4795286bc3530d11804ede5d7d79376494f0"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "4baed130e69489b17d22c788ee5b2c6b1b48abef4baafcafef530ed13de96932"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13+1/ImageMagick.v6.9.13.x86_64-linux-gnu-cxx03.tar.gz"
[[ImageMagick]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "626c5d0c95f85d1ff36b4ad8d8def4621b896dbb"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "27aa4a7a479d2ffc72853e0a70381087093263a4778aace3bcef04e2f7af7905"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13+1/ImageMagick.v6.9.13.x86_64-linux-gnu-cxx11.tar.gz"
[[ImageMagick]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9a43e38570646a1d8da9281d80c3cdedc6cc8a7c"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "8f1d77c513faf499a4ef4ff1b87bc61f7a857a1b91672f8804d516eb0968d965"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13+1/ImageMagick.v6.9.13.x86_64-linux-musl-cxx03.tar.gz"
[[ImageMagick]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6e408218d82f2e2e012d00a603d745a4aa4a8841"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "d427b511accb9f68fcae0b7799ec100096e64aa16209a2986e7837ee2ef8fc11"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13+1/ImageMagick.v6.9.13.x86_64-linux-musl-cxx11.tar.gz"
[[ImageMagick]]
arch = "x86_64"
git-tree-sha1 = "ab2717b1fba00e2445c087ec0134958a6991d2a9"
os = "freebsd"

    [[ImageMagick.download]]
    sha256 = "61688c552f5bb74e18a22d280da82593fc7bb5e52556e4f17c40d82162d9dbfc"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13+1/ImageMagick.v6.9.13.x86_64-unknown-freebsd.tar.gz"
[[ImageMagick]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b1f9b0ba12a27c85f2159cb058959a341fa31c3d"
os = "windows"

    [[ImageMagick.download]]
    sha256 = "97533830912e99d1879fbe9b21e8542f3043105e14fbe7ba3be6680b120862ed"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13+1/ImageMagick.v6.9.13.x86_64-w64-mingw32-cxx03.tar.gz"
[[ImageMagick]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fbb10ba437e25d4a8663e471f21a1bbd7227fd88"
os = "windows"

    [[ImageMagick.download]]
    sha256 = "9d80a21c79f2c3f64ac53b074dabb9c8afc7c89a9f900325ee7810ede0738493"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.13+1/ImageMagick.v6.9.13.x86_64-w64-mingw32-cxx11.tar.gz"
