[[ImageMagick]]
arch = "aarch64"
git-tree-sha1 = "2a05f425f2a9b1e6523f57f8ff882e762468c2ad"
os = "macos"

    [[ImageMagick.download]]
    sha256 = "d277366ccda143c8e6dd95d729ca4978142463bae2981e38beba12c5a236e7b0"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.12+3/ImageMagick.v6.9.12.aarch64-apple-darwin.tar.gz"
[[ImageMagick]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "46dc9456b3cb8089ff2dbd555232c97de948633d"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "f7175e10f5b5934eb1271e28a4b1286e2a4a131b71b045ac985491831076b430"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.12+3/ImageMagick.v6.9.12.aarch64-linux-gnu-cxx03.tar.gz"
[[ImageMagick]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ca613ec43dd2ad35f5691b7d417c6caa8daf394b"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "87f446019e7530309e25449eeb60a92cc5196bbe82433043063b9a81118087ec"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.12+3/ImageMagick.v6.9.12.aarch64-linux-gnu-cxx11.tar.gz"
[[ImageMagick]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "960058b261ebdf2ce9b0ca899b59acb973efa2c5"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "d39240f46095f1000d54ee604b411c039b1f8e7286a3055c63796276f3a4f04b"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.12+3/ImageMagick.v6.9.12.aarch64-linux-musl-cxx03.tar.gz"
[[ImageMagick]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ec35ab1ee7467cd15f114c535c2549b791ffe0e2"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "9eab996a3533f6dfde617be107fda390e03b1a26a9313a7e5a341d478024bacb"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.12+3/ImageMagick.v6.9.12.aarch64-linux-musl-cxx11.tar.gz"
[[ImageMagick]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5a11e119e1307250700a97751ff343972d649f1d"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "433d7f109d8293f54091bbc31dc89ca743403928e89864e1446784ee420f0225"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.12+3/ImageMagick.v6.9.12.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[ImageMagick]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c4e56cd52bd0f6165d498a4ba18f2d7cd9cab598"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "0cb903d5705ac7d7a61c2108bc04ae1b123c1d5dda30696b2d932d12acd014c6"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.12+3/ImageMagick.v6.9.12.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[ImageMagick]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "28342c7cc60b5c888ad93b0c59db0d9f1d8e2994"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "fc6adf5adc08b9060f3db164ce429bfd0ae52381de8931def016df2395d5d8f4"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.12+3/ImageMagick.v6.9.12.armv6l-linux-musleabihf-cxx03.tar.gz"
[[ImageMagick]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "50c80a6164246b30834e18cbcb4184b808466e1f"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "7be278e2558883776e7e0e14e6f0b1428237493bb9b893b08c8bd1969812e17f"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.12+3/ImageMagick.v6.9.12.armv6l-linux-musleabihf-cxx11.tar.gz"
[[ImageMagick]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "48ff5ac0de75c6309b1607d0ef3e3b97056ddbdc"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "1a10d98e0b248426897539b372e99d51cf55425c077cd3d0771315c9899ea7fc"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.12+3/ImageMagick.v6.9.12.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[ImageMagick]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fda658ad8a742ff48e108bfe9331b3be17b40fe5"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "f462aa0ffb4a1a93b37818dd83ab4f862f677d3728fa0cf226ba7c558afc9ed1"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.12+3/ImageMagick.v6.9.12.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[ImageMagick]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "36d5ec8a1b6d24f8b3a695020d320b04fc7cc20f"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "9b5bae07cb10fd112f9abadd6d49fd90995d128460286c3098b36881b13e10c4"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.12+3/ImageMagick.v6.9.12.armv7l-linux-musleabihf-cxx03.tar.gz"
[[ImageMagick]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "78984ca089984cd670b25f72ed2d07caf10dabda"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "b7102107ca4da2d867e28f068066cbf38845ef7cc2a86c82368c9f564ea254b6"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.12+3/ImageMagick.v6.9.12.armv7l-linux-musleabihf-cxx11.tar.gz"
[[ImageMagick]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5348d29aeb430243b6368bbb2c11d1dd6ffb5f0e"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "cdd0fe51dca058287bc8fbcb0e44079c4cdccd6e9e65b9586bb81bf93de4abc8"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.12+3/ImageMagick.v6.9.12.i686-linux-gnu-cxx03.tar.gz"
[[ImageMagick]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ce7e54a6ea2da99f3ac7d887d0012964009e1f45"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "f6646f8751ee457e8790fdce5887ba700123c7a0cc7b443567a948bb5abcd5ff"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.12+3/ImageMagick.v6.9.12.i686-linux-gnu-cxx11.tar.gz"
[[ImageMagick]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9af0bff75079ed57fb2605982b863e3da086dd7d"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "514179a051a0c173f54697c76998553032549b805d6032e3d4cda03b40fe900c"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.12+3/ImageMagick.v6.9.12.i686-linux-musl-cxx03.tar.gz"
[[ImageMagick]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "31389fe32564aff88ef16fd70b33307d11cfa581"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "cf438dc2f7e4d792306c2e8622dd0e7b13cbf7951cf1365cca5caffec792bb3d"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.12+3/ImageMagick.v6.9.12.i686-linux-musl-cxx11.tar.gz"
[[ImageMagick]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d308d3445dea92fd25cd3af64f677c480b281b4e"
os = "windows"

    [[ImageMagick.download]]
    sha256 = "279c690a9bec13eab828dbc2f716a8033b5e249a42d9c5a8c6dd27d9bd7592da"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.12+3/ImageMagick.v6.9.12.i686-w64-mingw32-cxx03.tar.gz"
[[ImageMagick]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5e570c8bc0f74a190ff8780ef8981a68f88ef4c6"
os = "windows"

    [[ImageMagick.download]]
    sha256 = "a572ec1a711afea25bad6c39d13218dc21dfffedd38e4d862f11af8ecd508a11"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.12+3/ImageMagick.v6.9.12.i686-w64-mingw32-cxx11.tar.gz"
[[ImageMagick]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2d7a85e7e940e0c8d2e1bd553fd4ac13a6f10195"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "1d70b466066368153bd79f3cfea82c9e1817172c69f9b9e9fa59c50f32b072f3"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.12+3/ImageMagick.v6.9.12.powerpc64le-linux-gnu-cxx03.tar.gz"
[[ImageMagick]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b1dd01f951cefc9d76a6368e6fb59592bc2bc98e"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "afa6c616f2ebaaa4881da3ba16a9c4a851c0a9f904fd2732008847cf9482cffe"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.12+3/ImageMagick.v6.9.12.powerpc64le-linux-gnu-cxx11.tar.gz"
[[ImageMagick]]
arch = "x86_64"
git-tree-sha1 = "367b6da33cb27a59373e0a6743550f6d74c78232"
os = "macos"

    [[ImageMagick.download]]
    sha256 = "43c08d2b1f231416e29c9d837ddfeab887af1f6d38c74c52fde4bf8000666a7b"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.12+3/ImageMagick.v6.9.12.x86_64-apple-darwin.tar.gz"
[[ImageMagick]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "86f221bf1ee2552cd7e94237bb27c57df5f05d41"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "bc64385800a8ebd4435bba15944aca2e40c8f513179ab1bec5e977f4381b5c5b"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.12+3/ImageMagick.v6.9.12.x86_64-linux-gnu-cxx03.tar.gz"
[[ImageMagick]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2582efc1374eed686290104aa1fd2bb6326005cf"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "1451484c72b0e7946472c9e995d88e1b0aafe9ce7b71607f0e8fbfe8df146709"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.12+3/ImageMagick.v6.9.12.x86_64-linux-gnu-cxx11.tar.gz"
[[ImageMagick]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ef1d4cff1b9c2db0f5da94157ee3492f8d6a591f"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "27bab1912715b8ac23692890c1faccdba38e9483b889a1f726426336383ef53d"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.12+3/ImageMagick.v6.9.12.x86_64-linux-musl-cxx03.tar.gz"
[[ImageMagick]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e71b898862c2f40fe0485d7104be68a266edf2ae"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "7ed567608e6ff4a27aefdf9037c992696e8117ef797322cd27aab7aa89766320"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.12+3/ImageMagick.v6.9.12.x86_64-linux-musl-cxx11.tar.gz"
[[ImageMagick]]
arch = "x86_64"
git-tree-sha1 = "f21f916c6d2fbdfbe263fbb59f09798516f2fdf7"
os = "freebsd"

    [[ImageMagick.download]]
    sha256 = "8cfe4b9dd6b933c827422951d113e24fd2cd30cb0ef913a0edf92beccca4b9b7"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.12+3/ImageMagick.v6.9.12.x86_64-unknown-freebsd.tar.gz"
[[ImageMagick]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3d9ea264feeedf171cd7d267a25981a9c919860a"
os = "windows"

    [[ImageMagick.download]]
    sha256 = "72a8350527b527d25bcb05bf95094a0f456bbca8d8834bcdbd7b533e3c12a564"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.12+3/ImageMagick.v6.9.12.x86_64-w64-mingw32-cxx03.tar.gz"
[[ImageMagick]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "12740e5ae5e9b354a37fd416e9a03511c18c8be3"
os = "windows"

    [[ImageMagick.download]]
    sha256 = "89f1f2973fe0d0948f1850362959e7a8b8f12c20526a6d97a4a0caebce9be5a8"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v6.9.12+3/ImageMagick.v6.9.12.x86_64-w64-mingw32-cxx11.tar.gz"
