[[ImageMagick]]
arch = "aarch64"
git-tree-sha1 = "0da128ca537701ddbb05dd85b09ce3c433b85305"
os = "macos"

    [[ImageMagick.download]]
    sha256 = "cd42e1d7e7fdfb8ff206e1dc2240d3a0fd8ba94c239765893e101bc472b13add"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v7.1.2002+0/ImageMagick.v7.1.2002.aarch64-apple-darwin.tar.gz"
[[ImageMagick]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4df8394e89a2086d1ee11784a97279b6a9997bc9"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "51367c2114e46ead764dc0acca9fd6e3c5bd611c1843b70f5ba3e43218342a07"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v7.1.2002+0/ImageMagick.v7.1.2002.aarch64-linux-gnu-cxx03.tar.gz"
[[ImageMagick]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e7e3d942a0b6dd60e7f1d6e8e0d0a19ce469407e"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "657e257ff2b640d520eafaab5f0822954a9a3b4fbaaa42c6c0a39ab662a16422"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v7.1.2002+0/ImageMagick.v7.1.2002.aarch64-linux-gnu-cxx11.tar.gz"
[[ImageMagick]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f4569d7df6fd106c48886d9a7d6bf5fb0a6ec92a"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "c5990859d512d6c89f1fc75c81f4cfa292beffc24dda814ec73df584c8010a73"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v7.1.2002+0/ImageMagick.v7.1.2002.aarch64-linux-musl-cxx03.tar.gz"
[[ImageMagick]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dd32b70f58e0abe38aa5d3d2e59b6a9615800244"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "7364ea6f9b472ba017a8a58f20e4c08fc9b93ac2296fce57872ad7e858152cf1"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v7.1.2002+0/ImageMagick.v7.1.2002.aarch64-linux-musl-cxx11.tar.gz"
[[ImageMagick]]
arch = "aarch64"
git-tree-sha1 = "e59cc4aec8c79a1960e702a8a1125e21171fb268"
os = "freebsd"

    [[ImageMagick.download]]
    sha256 = "84d8a44af40be670e722be36c26c58f2c9458ca779a4d2cc9fe9729ab10ca0d5"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v7.1.2002+0/ImageMagick.v7.1.2002.aarch64-unknown-freebsd.tar.gz"
[[ImageMagick]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f93e80bcc9a78728c593047ec7ba04aa34b75912"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "0de6c3ec2e608a3f83b9086bfd95a346680a7844dd47eab5ef59995e0f80d383"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v7.1.2002+0/ImageMagick.v7.1.2002.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[ImageMagick]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f27145e1fdd8f0c6b75dc19efc6103ed6b33089f"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "d1b1f44e38bbcdaf0f2b8063f9cf7b2aa49cb18e18fb6edbf44e8ef37d726f07"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v7.1.2002+0/ImageMagick.v7.1.2002.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[ImageMagick]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "432ef63afbbd402b4635a1c184718456fcd8fb20"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "0bf29ee672c89811d5e5fdedeb7e90a0230ee0fbf4f5d9bb1c9433c624abea6f"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v7.1.2002+0/ImageMagick.v7.1.2002.armv6l-linux-musleabihf-cxx03.tar.gz"
[[ImageMagick]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "98d785a94c4d562a342c999de2a7a3461f56ac3a"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "a6c22abc6ec1bbcfaf6234da525b774cbbed1bc9ce2505e89008c43d1d57ce84"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v7.1.2002+0/ImageMagick.v7.1.2002.armv6l-linux-musleabihf-cxx11.tar.gz"
[[ImageMagick]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "99c809c73d8b50e9498fcbc1d2b208c667ff8f37"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "82b73ab893c56bc38a6596d09f12f3347e7e51fd50f326aa1562401ab20966df"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v7.1.2002+0/ImageMagick.v7.1.2002.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[ImageMagick]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6c8a483a0bcd91140d7c8a08b448cefbd390c310"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "68cb9a1928ac2e2f636bd6bdb9e45a1a9c7497c07fb6b238f91951101ba81df2"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v7.1.2002+0/ImageMagick.v7.1.2002.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[ImageMagick]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bc7e1e8a6b52c128dd557a891965748e396139d3"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "8581a4842a0010eb885a65f0dcd6d5b2c4fbea96a4884c88b810c3e75087eec8"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v7.1.2002+0/ImageMagick.v7.1.2002.armv7l-linux-musleabihf-cxx03.tar.gz"
[[ImageMagick]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "82a9a546bfee86c2ba9a014677c4a60e279628be"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "38374c19d9ac83dd6fe701a5397b2b0f440afc78557188a944b875b5ebb88ac8"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v7.1.2002+0/ImageMagick.v7.1.2002.armv7l-linux-musleabihf-cxx11.tar.gz"
[[ImageMagick]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2b6e00d2a83cabca97d9354ead3ae69fdda3f16c"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "ae4565e54944174f90d37afed00c27c388494016806d8b284b042f5fc2555b46"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v7.1.2002+0/ImageMagick.v7.1.2002.i686-linux-gnu-cxx03.tar.gz"
[[ImageMagick]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4e7d7fb3f122eb3e00a98f9ce42b0b3798b71bd7"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "68cfc63af6754dfd3dea471635125f5f86235dc2a9b42f883dbcddb386e724e5"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v7.1.2002+0/ImageMagick.v7.1.2002.i686-linux-gnu-cxx11.tar.gz"
[[ImageMagick]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1e81ba84132aa6fd82597337af2056043c6381c9"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "fafc26294c3dad8c14a7bbbe86bce2c1ea3466fc538d52f6723825c38187384f"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v7.1.2002+0/ImageMagick.v7.1.2002.i686-linux-musl-cxx03.tar.gz"
[[ImageMagick]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "911f7fa92075670f2d0ee584f657bf8e437b18c1"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "686150533933f800ab0c3c23fc2993c5bc6f3d4c6e00b93db1350bdf84c6786d"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v7.1.2002+0/ImageMagick.v7.1.2002.i686-linux-musl-cxx11.tar.gz"
[[ImageMagick]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3174ce950bdb0b35eae0d95860a0dd915b98cf88"
os = "windows"

    [[ImageMagick.download]]
    sha256 = "d7324c83bb8eaf092ada1edf1d58b7ece2ab1b34ab2da34639df7eb4011ef55d"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v7.1.2002+0/ImageMagick.v7.1.2002.i686-w64-mingw32-cxx03.tar.gz"
[[ImageMagick]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d7e08f74bb6c0f0b8ea54ba7cd553aadc6fa8499"
os = "windows"

    [[ImageMagick.download]]
    sha256 = "9a8216eed72d6ca3a9d36e5222eb28f3716b255f2c4269a68b20485fd62bcad8"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v7.1.2002+0/ImageMagick.v7.1.2002.i686-w64-mingw32-cxx11.tar.gz"
[[ImageMagick]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8a521ed5b30a7278dacd775b5f60c0cf530b872a"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "690a2eb5ad454b92dc725a8e78af55bdc2a0df2f1fe663815a3548252bb7df6d"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v7.1.2002+0/ImageMagick.v7.1.2002.powerpc64le-linux-gnu-cxx03.tar.gz"
[[ImageMagick]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "04006c33b2345a6f02a752e07167d753787dd751"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "62dcb5e80f345190798800915f6e1b950c51bf23bee57eb0152b86178feecdc0"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v7.1.2002+0/ImageMagick.v7.1.2002.powerpc64le-linux-gnu-cxx11.tar.gz"
[[ImageMagick]]
arch = "riscv64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "de6ce88dd50dcc0a243f699c14bed8f4ce54fbcc"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "e2789b02f2bb560a4754f405c28f17c13561fd6ed8e182121993c7993c919604"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v7.1.2002+0/ImageMagick.v7.1.2002.riscv64-linux-gnu-cxx03.tar.gz"
[[ImageMagick]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bb7f7bf1308028546d81a5f87a8485d5c290d7cf"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "50426d576291c89e675fbda50495000f3b9a27e4e85cc7f1b35f6bac168fe1f9"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v7.1.2002+0/ImageMagick.v7.1.2002.riscv64-linux-gnu-cxx11.tar.gz"
[[ImageMagick]]
arch = "x86_64"
git-tree-sha1 = "5b10017d5bf84921a201380fb92a8cfaecc49926"
os = "macos"

    [[ImageMagick.download]]
    sha256 = "97f15b4c1b85660661a2e6c9f5153644f6bef4c11635bb2557116e98ca629bbc"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v7.1.2002+0/ImageMagick.v7.1.2002.x86_64-apple-darwin.tar.gz"
[[ImageMagick]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "abf546a610ee81a214f47d5c525cfaf73d97af70"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "e8d6ad3cc8bea239710fde2ed207c9a66eeb832cf262e5c1f428eccfc3cf9c0a"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v7.1.2002+0/ImageMagick.v7.1.2002.x86_64-linux-gnu-cxx03.tar.gz"
[[ImageMagick]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "688af3ead30681f97c7566e86b9e7ac70687d0e3"
libc = "glibc"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "2358f9e39666b821e25d65e7f4a27441585b24d5c6cf1539c2c85893b751e8b0"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v7.1.2002+0/ImageMagick.v7.1.2002.x86_64-linux-gnu-cxx11.tar.gz"
[[ImageMagick]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a8f20b73f39389583320f368708564dd06bc6741"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "e88eae7a5ba224215b4ce2d9b2be7dbba4fec7a3a5d5c796ecbbe39477b9ec89"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v7.1.2002+0/ImageMagick.v7.1.2002.x86_64-linux-musl-cxx03.tar.gz"
[[ImageMagick]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0c0d4634cf05b93d335eb589f5ea5ffd1ee9bdc5"
libc = "musl"
os = "linux"

    [[ImageMagick.download]]
    sha256 = "9bfe3fa67e7b6bf36b6ccd8851a5dd565feeba48c7e0ba032967238c4ef45a21"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v7.1.2002+0/ImageMagick.v7.1.2002.x86_64-linux-musl-cxx11.tar.gz"
[[ImageMagick]]
arch = "x86_64"
git-tree-sha1 = "f521826ae804b4e2c74963064ab2347069d97036"
os = "freebsd"

    [[ImageMagick.download]]
    sha256 = "7372defa7ba2fc3aebf77b7838f29a25ed00c91c55c236cc2f2a43f6c0c1358c"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v7.1.2002+0/ImageMagick.v7.1.2002.x86_64-unknown-freebsd.tar.gz"
[[ImageMagick]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2900fe27925d8d656766597f142279769ff23e52"
os = "windows"

    [[ImageMagick.download]]
    sha256 = "f377d508d1bd94342aaff3e0c81cad4420daf4999bf10b46f299dabd409cbc7a"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v7.1.2002+0/ImageMagick.v7.1.2002.x86_64-w64-mingw32-cxx03.tar.gz"
[[ImageMagick]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c691f035438c3fad1b217313d302496f734d070e"
os = "windows"

    [[ImageMagick.download]]
    sha256 = "fbfbd5c9eefb69cc7aa3495cc9d31a5f1e3277b12454268b9273a3300f5dace8"
    url = "https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/releases/download/ImageMagick-v7.1.2002+0/ImageMagick.v7.1.2002.x86_64-w64-mingw32-cxx11.tar.gz"
