# Autogenerated wrapper script for ImageMagick_jll for aarch64-apple-darwin
export identify, imagemagick_convert, libwand

using Zlib_jll
using libpng_jll
using JpegTurbo_jll
using Libtiff_jll
JLLWrappers.@generate_wrapper_header("ImageMagick")
JLLWrappers.@declare_executable_product(identify)
JLLWrappers.@declare_executable_product(imagemagick_convert)
JLLWrappers.@declare_library_product(libwand, "@rpath/libMagickWand-6.Q16.7.dylib")
function __init__()
    JLLWrappers.@generate_init_header(Zlib_jll, libpng_jll, JpegTurbo_jll, Libtiff_jll)
    JLLWrappers.@init_executable_product(
        identify,
        "bin/identify",
    )

    JLLWrappers.@init_executable_product(
        imagemagick_convert,
        "bin/convert",
    )

    JLLWrappers.@init_library_product(
        libwand,
        "lib/libMagickWand-6.Q16.7.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
